agriculture_domains = [
    {
        "Domain_Name": "Soil Health and Nutrient Management",
        "Angles": {
            "Soil Testing": "Questions about testing soil to determine nutrient status, pH, salinity or other soil properties and using results for recommendations.",
            "Soil Type": "Questions about suitability, characteristics or management recommendations for different soil types.",
            "Soil Health": "Questions concerning maintaining or improving physical, chemical or biological condition of soil.",
            "Nutrient Requirement": "Questions about the amount or type of nutrients required by a crop.",
            "Nutrient Deficiency": "Identification of nutrient deficiencies based on symptoms and recommendations for correction.",
            "Fertilizer Selection": "Choosing an appropriate fertilizer or fertilizer combination for a crop or situation.",
            "Fertilizer Dose": "Recommended quantity of fertilizer to apply per acre, hectare, plant or other unit.",
            "Fertilizer Source": "Specific fertilizer products or materials used to supply a required nutrient.",
            "Nutrient Role / Function": "Explains the role of a nutrient in plant growth, development, yield or quality.",
            "Application Method": "How fertilizer or nutrient inputs should physically be applied.",
            "Application Timing": "When fertilizer or nutrient inputs should be applied.",
            "Stage-specific Management": "Nutrient management recommendations linked to a particular crop growth stage.",
            "Soil-specific Recommendation": "Nutrient or fertilizer recommendations that change according to soil type or soil condition.",
            "Micronutrient Management": "Management of micronutrients such as zinc, boron, iron, manganese or copper.",
            "Organic Inputs": "Use and management of FYM, compost, vermicompost, green manure and other organic nutrient sources.",
            "Fertilizer Mixing / Compatibility": "Compatibility, sequence or method of mixing different fertilizers or inputs.",
            "Fertilizer Storage": "Proper storage conditions and handling of fertilizers to maintain quality.",
            "Safety & Precautions": "Precautions required during fertilizer handling, application and storage.",
            "Expected Benefits": "Expected crop, soil, yield or economic benefits from a nutrient-management practice."
        }
    },
    {
        "Domain_Name": "Irrigation and Water Management",
        "Angles": {
            "Water Requirement": "Quantity of water required by a crop or plant.",
            "Irrigation Scheduling": "Planning irrigation according to crop, soil, weather and growth stage.",
            "Irrigation Timing": "Appropriate time or interval for irrigation.",
            "Irrigation Method": "Method used to deliver water, such as flood, drip, sprinkler or furrow irrigation.",
            "Critical Irrigation Stages": "Crop growth stages at which adequate water is particularly important.",
            "Water Source": "Suitability or management of available water sources for agriculture.",
            "Water Quality": "Assessment or management of irrigation-water quality, including salinity or other constraints.",
            "Irrigation Dose / Quantity": "Amount of water to apply during an irrigation event.",
            "Irrigation Frequency": "How often irrigation should be carried out.",
            "Drainage": "Removal or management of excess water from agricultural land.",
            "Waterlogging Management": "Prevention, diagnosis and mitigation of excess water accumulation in the root zone.",
            "Drought / Water Stress": "Identification, prevention and management of crop stress caused by insufficient water.",
            "Flood Management": "Management of crops and fields affected by flooding or excessive water.",
            "Moisture Conservation": "Practices used to retain soil moisture and reduce water losses.",
            "Rainwater Harvesting": "Collection, storage and agricultural use of rainfall.",
            "Salinity Management": "Management of salt accumulation in soil or irrigation water and its effects on crops.",
            "Safety & Precautions": "Precautions related to irrigation equipment, water application and water management."
        }
    },
    {
        "Domain_Name": "Insect – Pest Management",
        "Angles": {
            "Pest Identification": "Identification of an insect or other pest affecting the crop.",
            "Pest Symptoms / Damage Symptoms": "Visible signs of pest attack or characteristic damage caused by a pest.",
            "Pest Biology / Life Cycle": "Information about pest development, life stages, reproduction and behaviour.",
            "Pest Identification by Stage": "Identification of pests based on egg, larval, nymph, pupal or adult stage.",
            "Pest Incidence": "Information about occurrence, severity or prevalence of a pest infestation.",
            "Favourable Conditions": "Environmental or crop conditions that favour pest development or infestation.",
            "Pest Survival and Spread": "How a pest survives between seasons and spreads within or between fields.",
            "Monitoring / Scouting": "Methods for regularly observing, detecting and assessing pest populations.",
            "Economic Threshold Level": "Pest population level at which control becomes economically justified.",
            "Prevention": "Practices used to prevent pest establishment or infestation.",
            "Cultural Control": "Crop-management practices used to suppress pest populations.",
            "Mechanical Control": "Physical removal, trapping or destruction of pests.",
            "Biological Control": "Use of predators, parasitoids, pathogens or other biological agents to control pests.",
            "Chemical Control": "Use of insecticides or other chemical products to control pests.",
            "Integrated Pest Management": "Combination of compatible cultural, mechanical, biological and chemical approaches.",
            "Insecticide Selection": "Choosing an appropriate insecticide for a specific pest and crop.",
            "Insecticide Dose": "Recommended concentration or quantity of insecticide.",
            "Application Method": "Method by which the pest-control treatment should be applied.",
            "Application Timing": "Appropriate timing or crop/pest stage for pest-control application.",
            "Resistance Management": "Practices for preventing or managing pest resistance to pesticides.",
            "Safety & Precautions": "Safe handling, application, storage and use precautions for pest-control measures."
        }
    },
    {
        "Domain_Name": "Disease Management",
        "Angles": {
            "Disease Identification": "Identification of the disease affecting a crop.",
            "Symptoms": "Visible signs and characteristic manifestations of a disease.",
            "Cause / Causal Agent": "Pathogen or other causal factor responsible for the disease.",
            "Disease Biology": "Characteristics and development of the disease-causing organism.",
            "Disease Cycle": "Sequential stages through which a disease develops and reproduces.",
            "Survival and Spread": "How the pathogen survives and moves within or between crops or fields.",
            "Favourable Conditions": "Environmental or crop conditions that favour disease development.",
            "Disease Incidence": "Level, frequency or severity of disease occurrence.",
            "Diagnosis / Confirmation": "Methods used to confirm suspected disease identification.",
            "Prevention": "Practices intended to prevent disease occurrence or establishment.",
            "Cultural Control": "Crop and field-management practices used to reduce disease.",
            "Biological Control": "Use of beneficial organisms or biological agents against disease.",
            "Chemical Control": "Use of fungicides, bactericides or other chemicals for disease management.",
            "Integrated Disease Management": "Combined use of multiple disease-management approaches.",
            "Fungicide Selection": "Selection of a suitable fungicide for a particular disease.",
            "Fungicide Dose": "Recommended quantity or concentration of fungicide.",
            "Application Method": "How the disease-control product should be applied.",
            "Application Timing": "Appropriate time or disease stage for treatment.",
            "Resistant Varieties": "Use of varieties with resistance or tolerance to a disease.",
            "Sanitation": "Removal or management of infected plant material, debris and other disease sources.",
            "Safety & Precautions": "Precautions for handling and applying disease-control products and practices."
        }
    },
    {
        "Domain_Name": "Seed and Variety Selection",
        "Angles": {
            "Variety Identification": "Identifying a crop variety from its name or characteristics.",
            "Variety Features / Characteristics": "Specific traits or distinguishing features of a variety.",
            "Variety Selection": "Choosing a suitable variety for a particular farming situation.",
            "Recommended Varieties": "Varieties officially or agronomically recommended for a crop, region or condition.",
            "High-Yielding Varieties": "Varieties specifically characterized by high yield potential.",
            "Disease / Pest Resistance": "Resistance or tolerance of a variety to pests or diseases.",
            "Stress Tolerance": "Ability of a variety to withstand drought, flooding, salinity, heat, cold or other stresses.",
            "Yield / Productivity": "Expected yield or production performance of a variety.",
            "Maturity / Duration": "Time required by a variety to reach maturity or harvest.",
            "Grain / Fruit Quality": "Quality characteristics such as grain type, aroma, size, colour, taste or market quality.",
            "Suitability": "Overall suitability of a variety for a specific farming condition.",
            "Agro-climatic Suitability": "Suitability of a variety for a particular climate or agro-climatic zone.",
            "Soil Suitability": "Suitability of a variety for particular soil conditions.",
            "Season Suitability": "Suitability of a variety for a particular growing season.",
            "Irrigation Suitability": "Suitability under irrigated, rainfed or specific water regimes.",
            "Sowing Window": "Appropriate period for sowing a variety.",
            "Seed Rate": "Recommended quantity of seed required for a specified area.",
            "Seed Quality": "Characteristics determining seed quality, viability, purity and germination potential.",
            "Seed Treatment": "Treatment of seed before sowing to improve establishment or protect against pests and diseases.",
            "Seed Source / Availability": "Information about where suitable or certified seed can be obtained.",
            "Seed Storage": "Conditions and practices for maintaining seed viability during storage."
        }
    },
    {
        "Domain_Name": "Cultural and Crop Management Practices",
        "Angles": {
            "Land Preparation": "Preparation of land before sowing or planting.",
            "Tillage": "Ploughing, harrowing and other soil-disturbance operations.",
            "Sowing / Planting": "Establishment of the crop through seed sowing or planting material.",
            "Sowing Time": "Recommended period for sowing or planting.",
            "Planting Method": "Technique used to establish the crop.",
            "Spacing": "Recommended distance between plants and/or rows.",
            "Seed Rate": "Quantity of seed required for crop establishment.",
            "Transplanting": "Moving nursery-raised seedlings into the main field.",
            "Nursery Management": "Production and management of seedlings before field planting.",
            "Crop Establishment": "Practices affecting successful emergence and establishment of the crop.",
            "Intercultural Operations": "Operations carried out between crop establishment and harvest.",
            "Earthing Up": "Moving soil around the plant base for support, root development or other purposes.",
            "Pruning / Training": "Manipulation of plant structure to regulate growth, canopy or productivity.",
            "Thinning": "Removal of excess plants to achieve desired plant population.",
            "Staking": "Providing physical support to plants.",
            "Crop Growth Stages": "Identification and management of different stages of crop development.",
            "Crop Calendar": "Timeline of major crop-management activities throughout the season.",
            "Crop Rotation": "Planned sequence of different crops on the same land over successive seasons.",
            "Intercropping": "Growing two or more crops together in a planned spatial arrangement.",
            "Mulching": "Covering soil with organic, synthetic or other materials to modify soil conditions.",
            "Crop-specific Practices": "Management practices specifically associated with a particular crop.",
            "Harvest Timing": "Determining the appropriate stage or time for harvesting.",
            "General Crop Management": "Broad recommendations covering overall crop production when no narrower practice applies."
        }
    },
    {
        "Domain_Name": "Organic and Natural Farming",
        "Angles": {
            "Organic Inputs": "Inputs permitted or commonly used in organic production systems.",
            "Organic Manure": "Use and management of FYM, compost and other organic nutrient sources.",
            "Compost": "Preparation and use of decomposed organic material as a soil amendment.",
            "Vermicompost": "Production and use of earthworm-based compost.",
            "Green Manure": "Growing and incorporating green plant material to improve soil fertility.",
            "Biofertilizers": "Use of beneficial microorganisms to improve nutrient availability or uptake.",
            "Biopesticides": "Biological or naturally derived products used for pest management.",
            "Botanical Extracts": "Plant-derived preparations used for pest or disease management.",
            "Natural Pest Control": "Non-synthetic or ecological methods for controlling pests.",
            "Natural Disease Control": "Natural or biological methods for managing crop diseases.",
            "Biological Control": "Use of living organisms or biological agents to suppress pests or pathogens.",
            "Natural Farming Preparations": "Preparation and use of locally produced natural farming inputs.",
            "Input Preparation": "Methods for preparing organic, biological or natural farming inputs.",
            "Input Dose": "Recommended quantity or concentration of an organic or natural input.",
            "Application Method": "Method of applying organic or natural inputs.",
            "Application Timing": "Appropriate time for applying the input.",
            "Soil Health": "Effects of organic or natural practices on soil condition.",
            "Certification": "Requirements and processes associated with organic certification.",
            "Organic Conversion": "Transitioning a farm from conventional to organic production.",
            "Natural Farming Practices": "Production practices based on natural or ecological farming principles.",
            "Safety & Precautions": "Safe preparation, handling and application of organic or natural inputs."
        }
    },
    {
        "Domain_Name": "Weed Management",
        "Angles": {
            "Weed Identification": "Identification of weed species or weed groups.",
            "Weed Types": "Classification of weeds such as grasses, sedges and broadleaf weeds.",
            "Weed Symptoms / Damage": "Crop effects or visible damage resulting from weed competition.",
            "Weed Identification by Crop Stage": "Identification of weeds based on their growth stage or crop stage.",
            "Weed Incidence": "Occurrence, density or severity of weed infestation.",
            "Favourable Conditions": "Conditions that encourage weed emergence and growth.",
            "Weed Life Cycle": "Growth, reproduction and seasonal survival characteristics of weeds.",
            "Prevention": "Practices used to prevent weed establishment or spread.",
            "Cultural Control": "Crop-management practices that suppress weed growth.",
            "Mechanical Control": "Physical removal or destruction of weeds using tools or machinery.",
            "Manual Weeding": "Removal of weeds by hand or manual tools.",
            "Mulching": "Use of a soil-covering material to suppress weed emergence.",
            "Biological Control": "Use of biological agents to suppress weeds.",
            "Herbicide Selection": "Selection of an appropriate herbicide for a weed-management situation.",
            "Herbicide Dose": "Recommended quantity or concentration of herbicide.",
            "Herbicide Application Method": "Technique used to apply a herbicide.",
            "Application Timing": "Appropriate time for herbicide application.",
            "Pre-emergence Control": "Weed control applied before weeds emerge.",
            "Post-emergence Control": "Weed control applied after weeds emerge.",
            "Integrated Weed Management": "Combination of cultural, mechanical, biological and chemical weed-control approaches.",
            "Herbicide Resistance": "Development or management of weed resistance to herbicides.",
            "Safety & Precautions": "Safe handling, application and storage of herbicides and other weed-control methods."
        }
    },
    {
        "Domain_Name": "Climate, Weather & Stress Management",
        "Angles": {
            "Weather Conditions": "Current or expected weather conditions affecting agriculture.",
            "Weather Forecast": "Forecast information relevant to agricultural operations.",
            "Temperature Stress": "Crop stress caused by temperatures outside the optimum range.",
            "Heat Stress": "Damage or physiological stress caused by excessive temperature.",
            "Cold / Frost Stress": "Damage caused by low temperature or frost.",
            "Drought Stress": "Crop stress resulting from prolonged or severe water shortage.",
            "Flood Stress": "Crop damage or stress caused by flooding.",
            "Waterlogging": "Stress resulting from prolonged saturation of the root zone.",
            "Salinity Stress": "Crop stress caused by excessive salts in soil or water.",
            "Wind Damage": "Crop damage caused by strong winds.",
            "Hail Damage": "Crop damage resulting from hailstorms.",
            "Excess Rainfall": "Crop and soil impacts caused by unusually heavy rainfall.",
            "Moisture Stress": "Plant stress caused by inadequate soil moisture availability.",
            "Climate Suitability": "Suitability of a crop or variety under a particular climatic condition.",
            "Weather-sensitive Crop Stages": "Crop stages particularly vulnerable to specific weather conditions.",
            "Stress Symptoms": "Visible or physiological symptoms associated with environmental stress.",
            "Stress Identification": "Determining the specific environmental stress affecting a crop.",
            "Prevention": "Measures taken before stress occurs to reduce potential damage.",
            "Mitigation Measures": "Actions taken to reduce the severity or impact of an ongoing stress.",
            "Recovery Measures": "Practices used to help crops recover after a stress event.",
            "Weather-based Advisory": "Farm recommendations generated according to current or forecast weather.",
            "Protective Measures": "Physical, agronomic or management measures used to protect crops from weather stress."
        }
    },
    {
        "Domain_Name": "Farm Tools & Mechanisation",
        "Angles": {
            "Tool / Equipment Identification": "Identifying an agricultural tool, implement or machine.",
            "Equipment Selection": "Choosing equipment appropriate for a specific farm operation.",
            "Machinery Selection": "Choosing suitable machinery based on crop, operation and farm conditions.",
            "Suitable Machinery": "Machinery recommendations for a particular agricultural task.",
            "Implements": "Information about agricultural implements and their uses.",
            "Function / Purpose": "What a tool, implement or machine is designed to accomplish.",
            "Capacity": "Working capacity, size or operational output of equipment.",
            "Specifications": "Technical characteristics and specifications of machinery or equipment.",
            "Operation / Usage": "How machinery or equipment should be operated or used.",
            "Calibration": "Adjusting equipment to deliver the intended quantity or application rate.",
            "Settings / Adjustment": "Appropriate machine settings for different operations or conditions.",
            "Application Method": "How machinery or equipment is used to perform an agricultural application.",
            "Maintenance": "Routine practices required to keep equipment functional.",
            "Repair / Troubleshooting": "Diagnosing and resolving equipment problems or failures.",
            "Fuel / Power Requirement": "Fuel, electricity, tractor power or other energy requirements.",
            "Cost / Economics": "Purchase, operating or economic considerations associated with machinery.",
            "Safety & Precautions": "Safe operation, handling and maintenance of agricultural machinery.",
            "Availability": "Information about where or how equipment can be accessed, rented or purchased."
        }
    },
    {
        "Domain_Name": "Post-Harvest Management & Storage",
        "Angles": {
            "Harvest Timing": "Determining when produce should be harvested.",
            "Harvest Method": "Method or technique used for harvesting.",
            "Post-harvest Handling": "Handling practices immediately after harvest to maintain quality.",
            "Cleaning": "Removal of soil, debris or unwanted material after harvest.",
            "Grading": "Classification of produce according to quality, size or other standards.",
            "Sorting": "Separation of produce based on quality, size, damage or other characteristics.",
            "Drying": "Reduction of moisture content after harvest.",
            "Moisture Level": "Appropriate moisture content for safe storage, processing or marketing.",
            "Processing": "Conversion of raw agricultural produce into processed products.",
            "Packaging": "Selection and use of suitable packaging materials and methods.",
            "Transportation": "Safe movement of agricultural produce from farm to storage, market or processing facility.",
            "Storage Method": "Appropriate technique or facility for storing agricultural produce.",
            "Storage Conditions": "Required temperature, humidity, ventilation and other storage conditions.",
            "Storage Duration": "Expected or recommended period for safe storage.",
            "Warehouse Management": "Management of agricultural produce within storage facilities.",
            "Pest Management in Storage": "Prevention and control of insects, rodents and other storage pests.",
            "Disease / Fungal Management in Storage": "Prevention and management of fungal or microbial deterioration during storage.",
            "Quality Maintenance": "Practices for preserving physical, nutritional and market quality after harvest.",
            "Shelf Life": "Period during which produce remains acceptable for intended use.",
            "Post-harvest Loss Reduction": "Practices aimed at minimizing quantity and quality losses after harvest.",
            "Safety & Precautions": "Safety measures during harvesting, handling, processing and storage."
        }
    },
    {
        "Domain_Name": "Market Prices, MSP & Marketing",
        "Angles": {
            "Market Price": "Current or reported price of an agricultural commodity.",
            "Price Trend": "Direction or pattern of commodity prices over time.",
            "MSP": "Minimum Support Price applicable to an agricultural commodity.",
            "Procurement Price": "Price at which government or authorized agencies procure agricultural produce.",
            "Market / Mandi Identification": "Identification of suitable markets or mandis for selling produce.",
            "Market Arrival": "Quantity and timing of produce arriving at a market.",
            "Demand and Supply": "Market demand and supply factors affecting agricultural prices.",
            "Price Comparison": "Comparison of prices across commodities, markets, locations or time periods.",
            "Crop Marketing": "Strategies and channels for selling agricultural produce.",
            "Selling Time": "Determining an appropriate time to sell produce.",
            "Market Selection": "Choosing a market based on price, distance, demand and other factors.",
            "Direct Marketing": "Selling produce directly to consumers, institutions or buyers.",
            "Collective Marketing": "Marketing through FPOs, cooperatives or farmer groups.",
            "Government Procurement": "Government mechanisms for purchasing agricultural produce.",
            "Quality and Price": "Relationship between produce quality/grade and market price.",
            "Transportation Cost": "Cost of moving produce to a market and its effect on returns.",
            "Profitability": "Revenue, cost and net-return considerations associated with marketing.",
            "Market Information": "Information required by farmers to make marketing decisions."
        }
    },
    {
        "Domain_Name": "Agricultural Schemes & Subsidies",
        "Angles": {
            "Scheme Identification": "Identifying the relevant government scheme for a farmer or activity.",
            "Eligibility": "Conditions a farmer or beneficiary must satisfy to access a scheme.",
            "Benefits": "Financial, material or service benefits provided under a scheme.",
            "Subsidy Amount": "Specific monetary subsidy available under a scheme.",
            "Subsidy Percentage": "Proportion of eligible expenditure covered by subsidy.",
            "Application Process": "Steps required to apply for a scheme or subsidy.",
            "Registration": "Process of registering as a beneficiary or applicant.",
            "Required Documents": "Documents needed to apply or establish eligibility.",
            "Application Deadline": "Last date or relevant period for submitting an application.",
            "Beneficiary Selection": "Process used to identify or approve beneficiaries.",
            "State-specific Schemes": "Schemes implemented by individual state governments.",
            "Central Schemes": "Schemes implemented by the Government of India.",
            "Input Subsidy": "Subsidies provided for agricultural inputs such as seed, fertilizer or other inputs.",
            "Machinery Subsidy": "Subsidies available for agricultural machinery and equipment.",
            "Irrigation Subsidy": "Financial assistance for irrigation systems or water-management infrastructure.",
            "Infrastructure Subsidy": "Assistance for agricultural infrastructure or facilities.",
            "Status / Tracking": "Checking the status of an application or benefit.",
            "Renewal": "Process of renewing a scheme, registration or benefit.",
            "Grievance / Support": "Mechanisms for complaints, appeals or assistance.",
            "Contact / Department": "Relevant government department, office or authority for assistance."
        }
    },
    {
        "Domain_Name": "Credit, Loan & Insurance",
        "Angles": {
            "Loan Eligibility": "Conditions required to qualify for an agricultural loan.",
            "Loan Types": "Different categories of agricultural credit or loans.",
            "Loan Amount": "Amount of credit available or eligible to the farmer.",
            "Interest Rate": "Interest charged on an agricultural loan.",
            "Repayment": "Terms and process for repaying agricultural credit.",
            "Tenure": "Duration of the loan.",
            "Application Process": "Steps required to apply for agricultural credit or insurance.",
            "Required Documents": "Documents needed for loan or insurance applications.",
            "Bank / Financial Institution": "Banks or financial institutions providing agricultural credit.",
            "Kisan Credit Card": "Information concerning KCC eligibility, limits, usage and related procedures.",
            "Crop Loan": "Short-term or crop-production credit.",
            "Agricultural Investment Loan": "Credit for longer-term agricultural assets and investments.",
            "Collateral / Security": "Security or collateral requirements for obtaining credit.",
            "Credit Subsidy": "Government assistance that reduces the cost or burden of agricultural credit.",
            "Insurance Eligibility": "Conditions under which a farmer or crop is eligible for insurance.",
            "Premium": "Amount payable by the farmer or other party for insurance coverage.",
            "Coverage": "Risks, crops, area or losses covered under an insurance policy.",
            "Claim Process": "Procedure for filing an insurance claim.",
            "Claim Settlement": "Processing and payment of an approved insurance claim.",
            "Loss Assessment": "Assessment or verification of crop or livestock losses for insurance purposes.",
            "Insurance Deadline": "Deadline for enrollment, premium payment or claim submission.",
            "Renewal": "Continuation or renewal of credit or insurance coverage.",
            "Grievance / Support": "Complaint resolution and assistance for credit or insurance issues."
        }
    },
    {
        "Domain_Name": "Others",
        "Angles": {
            "General Agriculture Query": "Agricultural question that does not fit a more specific domain or angle.",
            "Product-specific Query": "Question focused primarily on a named agricultural product or input.",
            "Location-specific Query": "Question where the primary information need concerns a particular location.",
            "Farmer-specific Advisory": "Advice tailored to a farmer's particular situation, resources or constraints.",
            "Clarification": "Request to explain, interpret or clarify existing agricultural information.",
            "Troubleshooting": "Diagnosis and resolution of a specific agricultural problem or operational issue.",
            "Comparison": "Comparison between two or more agricultural products, practices, varieties, technologies or options.",
            "Recommendation": "Request for a recommended option or course of action.",
            "Identification": "Identification of an unknown crop, variety, pest, disease, input, tool or other agricultural entity.",
            "Other / Unclassified": "Query that cannot reasonably be assigned to an existing angle."
        }
    },
    {
        "Domain_Name": "Capacity Building, Extension & Communication",
        "Angles": {
            "Training": "Information about agricultural training programmes or learning opportunities.",
            "Farmer Training": "Training specifically designed to improve farmers' knowledge or skills.",
            "Skill Development": "Development of practical, technical or entrepreneurial agricultural skills.",
            "Advisory Services": "Access to expert agricultural advice and recommendations.",
            "Extension Services": "Agricultural extension activities that transfer knowledge and technologies to farmers.",
            "Expert Consultation": "Seeking guidance or consultation from an agricultural expert.",
            "KVK Services": "Services, demonstrations, training and advisory support provided through KVKs.",
            "Demonstration": "Practical demonstration of an agricultural technology or practice.",
            "Awareness": "Information intended to increase awareness about agricultural practices, programmes or risks.",
            "Farmer Field School": "Participatory, field-based farmer learning programmes.",
            "Communication Material": "Manuals, brochures, videos, guides or other agricultural communication resources.",
            "Helpline / Support": "Agricultural helplines and support channels available to farmers.",
            "Digital Advisory": "Agricultural advice delivered through digital platforms or technologies.",
            "Mobile / App-based Advisory": "Agricultural advisory services delivered through mobile applications or mobile platforms.",
            "Training Schedule": "Timing, duration and schedule of agricultural training activities.",
            "Training Eligibility": "Requirements for participation in a training programme.",
            "Training Resources": "Educational materials and resources used for agricultural learning.",
            "Best Practices": "Recommended or demonstrated practices that improve agricultural outcomes.",
            "Knowledge Resources": "Sources of agricultural information, documentation and learning material."
        }
    },
    {
        "Domain_Name": "Rural Infrastructure",
        "Angles": {
            "Roads": "Rural roads and connectivity relevant to agricultural movement and access.",
            "Farm-to-Market Connectivity": "Infrastructure connecting farms with markets and collection centres.",
            "Warehousing": "Facilities and systems for storing agricultural commodities.",
            "Cold Storage": "Temperature-controlled storage for perishable agricultural produce.",
            "Irrigation Infrastructure": "Physical infrastructure used to provide or distribute irrigation water.",
            "Rural Electricity": "Availability and reliability of electricity for agricultural and rural activities.",
            "Agricultural Markets / Mandis": "Physical market infrastructure for buying and selling agricultural produce.",
            "Collection Centres": "Facilities where produce is aggregated before transport, processing or marketing.",
            "Processing Infrastructure": "Facilities and equipment used for agricultural processing and value addition.",
            "Transport Infrastructure": "Infrastructure supporting movement of inputs, machinery and agricultural produce.",
            "Digital Connectivity": "Internet and digital infrastructure supporting agricultural activities.",
            "Internet / Telecom": "Availability of telecommunications and internet services in rural areas.",
            "Farm Buildings": "Structures used for crop, livestock, machinery or input management.",
            "Community Infrastructure": "Shared infrastructure supporting agricultural or rural communities.",
            "Infrastructure Availability": "Availability and accessibility of required agricultural infrastructure.",
            "Infrastructure Subsidy": "Government financial assistance for development of agricultural infrastructure.",
            "Maintenance / Repair": "Maintenance, rehabilitation or repair of agricultural infrastructure."
        }
    }
]