import type { IQuestionFullData } from "@/types";

export type AnswerTrust =
  | "verified"
  | "expert_reviewed"
  | "ai_generated"
  | "awaiting_review";

export interface AnswerTrustInfo {
  label: string;
  description: string;
}

const hasUsableGoldenAnswer = (question: IQuestionFullData): boolean => {
  const text = question.referenceQuestionData?.text;
  return typeof text === "string" && text.trim().length > 0;
};

const hasExpertReviewedAnswer = (question: IQuestionFullData): boolean => {
  const finalAnswer = question.closedFinalAnswer;
  if (
    finalAnswer &&
    typeof finalAnswer.answer === "string" &&
    finalAnswer.answer.trim().length > 0
  ) {
    return true;
  }

  return (question.submission?.history ?? []).some((entry) => {
    const answer = entry?.answer;
    return (
      answer !== null &&
      answer !== undefined &&
      typeof answer.answer === "string" &&
      answer.answer.trim().length > 0
    );
  });
};

const hasAiAnswer = (question: IQuestionFullData): boolean => {
  const initial = question.aiInitialAnswer;
  const approved = question.aiApprovedAnswer;
  return (
    (typeof initial === "string" && initial.trim().length > 0) ||
    (typeof approved === "string" && approved.trim().length > 0)
  );
};

export const classifyAnswerTrust = (
  question: IQuestionFullData,
): AnswerTrust => {
  if (hasExpertReviewedAnswer(question)) return "expert_reviewed";
  if (hasUsableGoldenAnswer(question)) return "verified";
  if (hasAiAnswer(question)) return "ai_generated";
  return "awaiting_review";
};

export const ANSWER_TRUST_LABELS: Record<AnswerTrust, AnswerTrustInfo> = {
  verified: {
    label: "✓ Verified Expert Answer",
    description: "Answer matched with expert-verified agricultural knowledge.",
  },
  expert_reviewed: {
    label: "Expert-reviewed",
    description: "Answer has been reviewed by an agricultural expert.",
  },
  ai_generated: {
    label: "✦ AI-generated",
    description: "Answer was generated by AI and may require expert review.",
  },
  awaiting_review: {
    label: "Awaiting expert review",
    description: "No final answer is available yet.",
  },
};
