import type { Segment, KpiCard } from "./types";

export const DASHBOARD_DATA = {
  meta: { season: "Kharif 2025", lastSync: "2 min ago", datasetVersion: "GD-2025-Q3.14", llmVersion: "v2.4.1", p0Bugs: 3 },
  kpiRow1: [
    { id: "dau", label: "Active farmers (DAU)", value: "4.82 L", delta: "+18% vs last month", deltaDir: "up" as const, accentColor: "#3AAA5A", sparkPoints: [22,20,22,18,19,15,13,14,10,11,8,7,5] },
    { id: "queries", label: "Daily queries", value: "1.24 L", delta: "+31% week-on-week", deltaDir: "up" as const, accentColor: "#378ADD", sparkPoints: [24,22,20,22,18,20,16,18,14,12,10,8,6] },
    { id: "session", label: "Avg session duration", value: "6.4 min", delta: "Stable this week", deltaDir: "neutral" as const, accentColor: "#EF9F27", sparkPoints: [14,12,15,13,12,14,13,14,12,13,14,12,13] },
    { id: "bugs", label: "Critical bugs open", value: "7", delta: "Needs immediate action", deltaDir: "down" as const, accentColor: "#E24B4A", badges: [{ label: "3 P0", variant: "red" as const }, { label: "4 P1", variant: "amber" as const }] },
  ] as KpiCard[],
  kpiRow2: [
    { id: "csat", label: "CSAT rating", value: "4.2 ★", delta: "+0.3 pts this month", deltaDir: "up" as const, accentColor: "#1D9E75" },
    { id: "repeatQuery", label: "Repeat query rate", value: "28%", delta: "Target: <10% · gap", deltaDir: "down" as const, accentColor: "#EF9F27", valueColor: "#854F0B" },
    { id: "voice", label: "Voice usage share", value: "61%", delta: "Primary mode", deltaDir: "up" as const, accentColor: "#378ADD" },
    { id: "states", label: "States active", value: "19 / 28", delta: "3 new states added", deltaDir: "up" as const, accentColor: "#7C6FD4" },
  ] as KpiCard[],
  channelSplit: [
    { label: "Voice", pct: 61, color: "#3AAA5A" },
    { label: "Text app", pct: 39, color: "#378ADD" },
    // { label: "KCC agent", pct: 9, color: "#EF9F27" },
    // { label: "IVRS call", pct: 6, color: "#7C6FD4" },
  ],
  voiceAccuracy: [
    { lang: "Hindi", pct: 84, color: "#3AAA5A" },
    { lang: "Telugu", pct: 79, color: "#3AAA5A" },
    { lang: "Marathi", pct: 72, color: "#EF9F27" },
    { lang: "Bhojpuri", pct: 51, color: "#E24B4A" },
  ],
  queryCategories: [
    { label: "Pest & disease", pct: 34, color: "#E24B4A", valueColor: "#A32D2D" },
    { label: "Fertilizer dosage", pct: 28, color: "#EF9F27", valueColor: "#633806" },
    { label: "Irrigation timing", pct: 18, color: "#378ADD" },
    { label: "Crop selection", pct: 12, color: "#3AAA5A" },
    { label: "Govt. schemes", pct: 8, color: "#7C6FD4" },
  ],
  farmerSegments: [
    { id: "power", label: "Power farmers", users: "82,400", status: "Active", statusVariant: "green" as const, description: "High-frequency users querying 5+ times/week. Core advocates.", dau: 82400, retention: 91, queryRate: 8.2, topCrop: "Paddy" },
    { id: "casual", label: "Casual seekers", users: "2.14 L", status: "Core", statusVariant: "blue" as const, description: "Majority segment. 2–4 queries/week. Good retention.", dau: 214000, retention: 74, queryRate: 3.1, topCrop: "Cotton" },
    { id: "repeat", label: "Repeat askers", users: "54,300", status: "Gap", statusVariant: "amber" as const, description: "Same query repeated — answers not resonating. UX gap.", dau: 54300, retention: 48, queryRate: 4.8, topCrop: "Maize" },
    { id: "silent", label: "Silent lurkers", users: "98,700", status: "Re-engage", statusVariant: "red" as const, description: "Opened app but rarely ask. Need push nudges.", dau: 98700, retention: 22, queryRate: 0.4, topCrop: "Wheat" },
    { id: "churned", label: "Churned users", users: "31,200", status: "Win-back", statusVariant: "red" as const, description: "No activity 30+ days. Requires win-back campaign.", dau: 31200, retention: 0, queryRate: 0, topCrop: "—" },
    { id: "institutional", label: "Institutional", users: "1,600", status: "B2G", statusVariant: "blue" as const, description: "Government & extension officers. B2G relationship.", dau: 1600, retention: 88, queryRate: 12.4, topCrop: "All" },
    { id: "new_adopters", label: "New adopters", users: "45,800", status: "Onboard", statusVariant: "green" as const, description: "Joined in last 30 days. Need onboarding nudges.", dau: 45800, retention: 55, queryRate: 2.1, topCrop: "Soybean" },
    { id: "seasonal", label: "Seasonal users", users: "67,500", status: "Monitor", statusVariant: "amber" as const, description: "Active only during sowing/harvest. Seasonal engagement.", dau: 67500, retention: 38, queryRate: 1.8, topCrop: "Rice" },
    { id: "premium", label: "Premium growers", users: "12,300", status: "VIP", statusVariant: "green" as const, description: "High-value commercial farmers. Priority support needed.", dau: 12300, retention: 94, queryRate: 9.6, topCrop: "Sugarcane" },
  ] as Segment[],
  alerts: [
    { id: 1, level: "critical" as const, title: "LLM dosage hallucination · ACE-079", desc: "Wrong pesticide dosage for paddy BLB · 612 farmers affected" },
    { id: 2, level: "critical" as const, title: "LLM dosage hallucination · ACE-079", desc: "Wrong pesticide dosage for paddy BLB · 612 farmers affected" },
    { id: 3, level: "critical" as const, title: "LLM dosage hallucination · ACE-079", desc: "Wrong pesticide dosage for paddy BLB · 612 farmers affected" },
    { id: 4, level: "critical" as const, title: "LLM dosage hallucination · ACE-079", desc: "Wrong pesticide dosage for paddy BLB · 612 farmers affected" },
    { id: 5, level: "critical" as const, title: "Voice crash Android 10 (2G)", desc: "18,000 users in UP, MP · 34% crash rate per session" },
    { id: 6, level: "critical" as const, title: "Voice crash Android 10 (2G)", desc: "18,000 users in UP, MP · 34% crash rate per session" },
    { id: 7, level: "warn" as const, title: "Dataset staleness · 9 days", desc: "Crop calendar showing last year's sowing dates for 6 crops" },
    { id: 8, level: "info" as const, title: "Push notification delivery at 38%", desc: "Firebase token refresh failure · seasonal alerts missed" },
    { id: 9, level: "info" as const, title: "Push notification delivery at 38%", desc: "Firebase token refresh failure · seasonal alerts missed" },
  ],
  geoStates: [
    { abbr: "UP", val: "1.2L", opacity: 0.9 }, { abbr: "MH", val: "94k", opacity: 0.8 }, { abbr: "MP", val: "86k", opacity: 0.75 },
    { abbr: "AP", val: "74k", opacity: 0.65 }, { abbr: "TN", val: "62k", opacity: 0.55 }, { abbr: "RJ", val: "58k", opacity: 0.48 },
    { abbr: "HR", val: "52k", opacity: 0.42 }, { abbr: "KA", val: "48k", opacity: 0.38 }, { abbr: "WB", val: "44k", opacity: 0.32 },
    { abbr: "GJ", val: "42k", opacity: 0.28 }, { abbr: "PB", val: "36k", opacity: 0.22 }, { abbr: "BR", val: "31k", opacity: 0.15 },
    { abbr: "OR", val: "28k", opacity: 0.13 }, { abbr: "JH", val: "24k", opacity: 0.11 }, { abbr: "CG", val: "21k", opacity: 0.10 },
    { abbr: "UK", val: "18k", opacity: 0.09 }, { abbr: "HP", val: "15k", opacity: 0.08 }, { abbr: "AS", val: "12k", opacity: 0.06 },
  ],
  healthPillars: [
    { label: "Advisory accuracy", score: 82, color: "#3AAA5A" },
    { label: "App stability", score: 74, color: "#3AAA5A" },
    { label: "User retention", score: 61, color: "#EF9F27" },
    { label: "Geo reach", score: 58, color: "#EF9F27" },
    { label: "Content coverage", score: 66, color: "#EF9F27" },
    { label: "UX satisfaction", score: 68, color: "#EF9F27" },
  ],
};
