/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as CallAgentDashboardIndexRouteImport } from './routes/call-agent-dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)

const CallAgentDashboardIndexRoute = CallAgentDashboardIndexRouteImport.update({
  id: '/call-agent-dashboard/',
  path: '/call-agent-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-agent-dashboard/': {
      id: '/call-agent-dashboard/'
      path: '/call-agent-dashboard'
      fullPath: '/call-agent-dashboard'
      preLoaderRoute: typeof CallAgentDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

export const routeTree = rootRouteImport.addChildren([
  IndexRoute,
  AuthIndexRoute,
  CallAgentDashboardIndexRoute,
])
