// export const CROPS = ["Paddy", "Wheat"];
export const CROPS = 
[
  'Coconut',
  'Coriander',
  'Cotton',
  'Crop Production',
  'Cumin',
  'Dairy Cow',
  'Drumstick',
  'Fodder Maize',
  'Garlic',
  'General',
  'Gram',
  'GramChick',
  'Groundnut',
  'Indian rapeseed and mustard yellow sarson',
  'Lentil Masur',
  'Linseed alsi',
  'Maize',
  'Mustard',
  'N/A',
  'Not specified',
  'Onion',
  'Paddy',
  'Paddy (Dhan)',
  'Poplar',
  'Poplar (Agroforestry)',
  'Potato',
  'Potatoes',
  'Raya Indian Mustard',
  'Rice',
  'Sugarcane',
  'Summer Vegetables',
  'Tomato',
  'Toria',
  'Turmeric',
  'Unknown',
  'Weather',
  'Wheat',
  'apple',
  'banana',
  'bhindi',
  'cotton',
  'groundnut',
  'maize',
  'paddy',
  'potato',
  'rice',
  'soybean',
  'sugarcane',
  'unknown',
  'wheat',
  'ਧਾਨ'
]
export const DOMAINS = [
  "Agriculture Mechanization",
  "Bio-Pesticides and Bio-Fertilizers",
  "Crop Insurance",
  "Cultural Practices",
  "Fertilizer Use and Availability",
  "Field Preparation",
  "Nutrient Management",
  "Organic Farming",
  "Plant Protection",
  "Post Harvest Preservation",
  "Seeds",
  "Soil Health Card",
  "Soil Testing",
  "Sowing Time and Weather",
  "Storage",
  "Varieties",
  "Water Management",
  "Weed Management",
  "Market Information"
];
export const STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
].sort();

export const SEASONS = [
  "Kharif",
  "Rabi",
  "Zaid",

  // Additional Indian sub-seasons
  "Pre-Kharif",
  "Post-Kharif",
  "Pre-Rabi",
  "Zaid Rabi",

  // General/global seasons
  "Spring",
  "Summer",
  "Autumn",
  "Winter",
  "Monsoon",
  "Dry Season",
  "Wet Season"
];

export const Review_Level=[
  "Level 1",
  "Level 2",
  "Level 3",
  "Level 4",
  "Level 5",
  "Level 6",
  "Level 7",
  "Level 8",
  "Level 9"

]
export const STATUS=[
  "open",
  "in-review",
  "delayed",
  "closed",
  "re-routed"
]
export const Review_Level_QAI=[
  "Author",
  "Level 1",
  "Level 2",
  "Level 3",
  "Level 4",
  "Level 5",
  "Level 6",
  "Level 7",
  "Level 8",
  "Level 9"

]
