import 'dotenv/config';
import { MongoClient } from 'mongodb';
import XLSX from 'xlsx';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// ============================================================
// CONFIGURATION
// ============================================================

const MONGO_URI = process.env.DB_URL || '';
const DB_NAME = process.env.DB_NAME || 'agriai';

const QUESTIONS_COLLECTION = 'questions';

const BATCH_SIZE = 500;

// ============================================================
// FILE PATHS
// ============================================================

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Existing report generated by normalise-domain.js
const REPORT_FILE_PATH = path.join(
  __dirname,
  '..',
  'domain-diff-report.json'
);

// Generated Excel file
const OUTPUT_FILE_PATH = path.join(
  __dirname,
  '..',
  'unmapped-domain-questions.xlsx'
);


// ============================================================
// VALIDATION
// ============================================================

if (!MONGO_URI) {
  throw new Error(
    '❌ DB_URL is not defined in the environment.'
  );
}


// ============================================================
// HELPERS
// ============================================================

function normalizeDomain(domain) {
  return String(domain || '')
    .trim()
    .replace(/\s+/g, ' ')
    .toLowerCase();
}


// ============================================================
// LOAD UNMAPPED DOMAINS
// ============================================================

function loadUnmappedDomains() {
  console.log(
    '📖 Reading domain diff report...'
  );

  if (!fs.existsSync(REPORT_FILE_PATH)) {
    throw new Error(
      `❌ Report file not found:\n${REPORT_FILE_PATH}`
    );
  }

  const report = JSON.parse(
    fs.readFileSync(
      REPORT_FILE_PATH,
      'utf8'
    )
  );

  if (!Array.isArray(report.unmappedDomains)) {
    throw new Error(
      '❌ unmappedDomains not found in domain-diff-report.json'
    );
  }

  const unmappedDomains = report.unmappedDomains
    .map(item => {
      // Supports:
      // { domain: "Plant Protection" }
      //
      // and also plain strings, just in case.
      if (
        typeof item === 'string'
      ) {
        return item;
      }

      return item?.domain;
    })
    .filter(Boolean);

  console.log(
    `✅ Loaded ${unmappedDomains.length} unmapped domains.\n`
  );

  console.log(
    'Unmapped domains to find:\n'
  );

  for (const domain of unmappedDomains) {
    console.log(`  - ${domain}`);
  }

  console.log('\n');

  return unmappedDomains;
}


// ============================================================
// EXPORT QUESTIONS
// ============================================================

async function exportUnmappedDomainQuestions() {
  const client = new MongoClient(MONGO_URI);

  try {
    // --------------------------------------------------------
    // Load unmapped domains
    // --------------------------------------------------------

    const unmappedDomains =
      loadUnmappedDomains();

    if (unmappedDomains.length === 0) {
      console.log(
        '⚠️ No unmapped domains found in the report.'
      );

      return;
    }


    // --------------------------------------------------------
    // Create normalized lookup Set
    // --------------------------------------------------------

    const unmappedDomainSet =
      new Set(
        unmappedDomains.map(
          normalizeDomain
        )
      );


    // --------------------------------------------------------
    // Connect
    // --------------------------------------------------------

    console.log(
      '🚀 Connecting to MongoDB...'
    );

    await client.connect();

    console.log(
      '✅ Connected to MongoDB successfully.\n'
    );

    const db = client.db(DB_NAME);

    const questionsCollection =
      db.collection(
        QUESTIONS_COLLECTION
      );


    // --------------------------------------------------------
    // Count questions
    // --------------------------------------------------------

    const totalQuestions =
      await questionsCollection.countDocuments({
        'details.domain': {
          $type: 'array',
        },
      });

    console.log(
      `🔍 Questions to check: ${totalQuestions}`
    );

    console.log(
      `📦 Batch size: ${BATCH_SIZE}\n`
    );


    // --------------------------------------------------------
    // Result rows
    // --------------------------------------------------------

    const excelRows = [];

    let processedQuestions = 0;
    let matchedQuestions = 0;

    let lastId = null;


    // ========================================================
    // PROCESS IN BATCHES
    // ========================================================

    while (true) {
      const query = {
        'details.domain': {
          $type: 'array',
        },
      };

      // Cursor pagination
      if (lastId) {
        query._id = {
          $gt: lastId,
        };
      }


      // ------------------------------------------------------
      // Fetch batch
      // ------------------------------------------------------

      const questions =
        await questionsCollection
          .find(
            query,
            {
              projection: {
                _id: 1,
                question: 1,
                details: 1,
              },
            }
          )
          .sort({
            _id: 1,
          })
          .limit(BATCH_SIZE)
          .toArray();


      if (questions.length === 0) {
        break;
      }


      // ======================================================
      // CHECK QUESTIONS
      // ======================================================

      for (const question of questions) {
        const domains =
          question?.details?.domain;

        if (!Array.isArray(domains)) {
          continue;
        }


        // ----------------------------------------------------
        // Find unmapped domains in this question
        // ----------------------------------------------------

        const matchingUnmappedDomains =
          domains.filter(domain =>
            unmappedDomainSet.has(
              normalizeDomain(domain)
            )
          );


        if (
          matchingUnmappedDomains.length === 0
        ) {
          continue;
        }


        matchedQuestions++;


        // ----------------------------------------------------
        // Details
        // ----------------------------------------------------

        const details =
          question.details || {};


        // ----------------------------------------------------
        // Create Excel row
        // ----------------------------------------------------

        excelRows.push({
          'Question ID':
            String(question._id),

          'Question':
            question.question || '',

          'Unmapped Domains':
            matchingUnmappedDomains.join(
              ', '
            ),

          'State':
            details.state || '',

          'District':
            details.district || '',

          'Crop':
            typeof details.crop === 'object'
              ? JSON.stringify(details.crop)
              : details.crop || '',

          'Season':
            details.season || '',

          'All Domains':
            domains.join(', '),

          'Details':
            JSON.stringify(
              details,
              null,
              2
            ),
        });
      }


      // ------------------------------------------------------
      // Progress
      // ------------------------------------------------------

      processedQuestions +=
        questions.length;

      lastId =
        questions[
          questions.length - 1
        ]._id;

      const percentage =
        totalQuestions === 0
          ? 100
          : (
              (processedQuestions /
                totalQuestions) *
              100
            ).toFixed(2);

      console.log(
        `📊 Progress: ${processedQuestions}/${totalQuestions} (${percentage}%) | Matched: ${matchedQuestions}`
      );
    }


    // ========================================================
    // NO RESULTS
    // ========================================================

    if (excelRows.length === 0) {
      console.log(
        '\n⚠️ No questions were found containing the unmapped domains.'
      );

      return;
    }


    // ========================================================
    // CREATE EXCEL
    // ========================================================

    console.log(
      '\n📊 Creating Excel report...'
    );

    const worksheet =
      XLSX.utils.json_to_sheet(
        excelRows
      );


    // --------------------------------------------------------
    // Column widths
    // --------------------------------------------------------

    worksheet['!cols'] = [
      {
        wch: 28,
      },
      {
        wch: 70,
      },
      {
        wch: 35,
      },
      {
        wch: 20,
      },
      {
        wch: 25,
      },
      {
        wch: 30,
      },
      {
        wch: 25,
      },
      {
        wch: 50,
      },
      {
        wch: 80,
      },
    ];


    // --------------------------------------------------------
    // Freeze header row
    // --------------------------------------------------------

    worksheet['!freeze'] = {
      xSplit: 0,
      ySplit: 1,
    };


    // --------------------------------------------------------
    // Create workbook
    // --------------------------------------------------------

    const workbook =
      XLSX.utils.book_new();

    XLSX.utils.book_append_sheet(
      workbook,
      worksheet,
      'Unmapped Questions'
    );


    // --------------------------------------------------------
    // Write Excel file
    // --------------------------------------------------------

    XLSX.writeFile(
      workbook,
      OUTPUT_FILE_PATH
    );


    // ========================================================
    // FINAL SUMMARY
    // ========================================================

    console.log('\n');

    console.log(
      '=================================================='
    );

    console.log(
      '          UNMAPPED DOMAIN REPORT'
    );

    console.log(
      '=================================================='
    );

    console.log(
      `Questions checked : ${processedQuestions}`
    );

    console.log(
      `Questions found   : ${matchedQuestions}`
    );

    console.log(
      `Excel rows        : ${excelRows.length}`
    );

    console.log(
      `Unmapped domains  : ${unmappedDomains.length}`
    );

    console.log(
      `\n📄 Excel saved to:`
    );

    console.log(
      OUTPUT_FILE_PATH
    );

    console.log(
      '\n✅ Report generation completed.'
    );
  } catch (error) {
    console.error(
      '\n🔴 Error generating unmapped domain report:',
      error
    );
  } finally {
    await client.close();

    console.log(
      '\n🔌 Disconnected from MongoDB.'
    );
  }
}


// ============================================================
// RUN
// ============================================================

exportUnmappedDomainQuestions();