// import 'dotenv/config';
// import { MongoClient } from 'mongodb';
// import fs from 'fs';
// import path from 'path';
// import { fileURLToPath } from 'url';

// // ============================================================
// // CONFIGURATION
// // ============================================================

// const MONGO_URI = process.env.DB_URL || '';
// const DB_NAME = process.env.DB_NAME || 'agriai';

// const QUESTIONS_COLLECTION = 'questions';

// // The report generated by normalise-domain.js
// const __filename = fileURLToPath(import.meta.url);
// const __dirname = path.dirname(__filename);

// const REPORT_FILE_PATH = path.join(
//   __dirname,
//   '..',
//   'domain-diff-report.json'
// );

// // Safety switch
// // false = only show what will be updated
// // true  = actually update MongoDB
// const PERFORM_UPDATE = false;


// // ============================================================
// // VALIDATION
// // ============================================================

// if (!MONGO_URI) {
//   throw new Error(
//     '❌ DB_URL is not defined in the environment.'
//   );
// }


// // ============================================================
// // LOAD REPORT
// // ============================================================

// function loadDomainReport() {
//   console.log('📖 Reading domain diff report...');

//   if (!fs.existsSync(REPORT_FILE_PATH)) {
//     throw new Error(
//       `❌ Report file not found:\n${REPORT_FILE_PATH}`
//     );
//   }

//   const report = JSON.parse(
//     fs.readFileSync(REPORT_FILE_PATH, 'utf8')
//   );

//   if (!Array.isArray(report.mappedDomains)) {
//     throw new Error(
//       '❌ mappedDomains not found in domain-diff-report.json'
//     );
//   }

//   console.log(
//     `✅ Loaded ${report.mappedDomains.length} verified mappings.\n`
//   );

//   return report;
// }


// // ============================================================
// // BUILD MAPPING
// // ============================================================

// function normalizeDomain(domain) {
//   return String(domain || '')
//     .trim()
//     .replace(/\s+/g, ' ')
//     .toLowerCase();
// }

// function buildMapping(mappedDomains) {
//   const mapping = new Map();

//   for (const item of mappedDomains) {
//     if (
//       !item.originalDomain ||
//       !item.standardizedDomain
//     ) {
//       continue;
//     }

//     const originalKey = normalizeDomain(
//       item.originalDomain
//     );

//     mapping.set(
//       originalKey,
//       item.standardizedDomain
//     );
//   }

//   return mapping;
// }


// // ============================================================
// // UPDATE QUESTIONS
// // ============================================================

// async function updateQuestionDomains() {
//   const client = new MongoClient(MONGO_URI);

//   try {
//     // --------------------------------------------------------
//     // Load verified mappings
//     // --------------------------------------------------------

//     const report = loadDomainReport();

//     const domainMapping = buildMapping(
//       report.mappedDomains
//     );

//     if (domainMapping.size === 0) {
//       console.log(
//         '⚠️ No mapped domains available for update.'
//       );
//       return;
//     }

//     console.log('🔄 Mappings that will be used:\n');

//     for (const [original, standardized] of domainMapping) {
//       console.log(
//         `${original} -> ${standardized}`
//       );
//     }

//     console.log('\n');


//     // --------------------------------------------------------
//     // Connect MongoDB
//     // --------------------------------------------------------

//     console.log('🚀 Connecting to MongoDB...');

//     await client.connect();

//     console.log(
//       '✅ Connected to MongoDB successfully.\n'
//     );

//     const db = client.db(DB_NAME);

//     const questionsCollection = db.collection(
//       QUESTIONS_COLLECTION
//     );


//     // --------------------------------------------------------
//     // Find questions containing at least one mapped domain
//     // --------------------------------------------------------

//     const mappedOriginalDomains = [
//       ...domainMapping.keys(),
//     ];

//     const questions = await questionsCollection
//       .find(
//         {
//           'details.domain': {
//             $type: 'array',
//           },
//         },
//         {
//           projection: {
//             _id: 1,
//             'details.domain': 1,
//           },
//         }
//       )
//       .toArray();

//     console.log(
//       `🔍 Checking ${questions.length} questions...\n`
//     );


//     // --------------------------------------------------------
//     // Prepare updates
//     // --------------------------------------------------------

//     const operations = [];

//     let questionsToUpdate = 0;
//     let domainsToUpdate = 0;


//     for (const question of questions) {
//       const domains = question?.details?.domain;

//       if (!Array.isArray(domains)) {
//         continue;
//       }

//       let hasChanges = false;
//       let changedCount = 0;

//       const updatedDomains = domains.map(domain => {
//         const normalized = normalizeDomain(domain);

//         const standardized =
//           domainMapping.get(normalized);

//         if (standardized) {
//           hasChanges = true;
//           changedCount++;

//           return standardized;
//         }

//         return domain;
//       });


//       // ------------------------------------------------------
//       // Remove duplicates after standardization
//       // ------------------------------------------------------

//       const uniqueDomains = [
//         ...new Map(
//           updatedDomains.map(domain => [
//             normalizeDomain(domain),
//             domain,
//           ])
//         ).values(),
//       ];


//       // ------------------------------------------------------
//       // Only update if something actually changed
//       // ------------------------------------------------------

//       if (hasChanges) {
//         questionsToUpdate++;
//         domainsToUpdate += changedCount;

//         operations.push({
//           updateOne: {
//             filter: {
//               _id: question._id,
//             },
//             update: {
//               $set: {
//                 'details.domain': uniqueDomains,
//               },
//             },
//           },
//         });


//         // ----------------------------------------------------
//         // Print what is going to change
//         // ----------------------------------------------------

//         console.log(
//           `Question: ${question._id}`
//         );

//         console.log(
//           `  OLD: ${JSON.stringify(domains)}`
//         );

//         console.log(
//           `  NEW: ${JSON.stringify(uniqueDomains)}`
//         );

//         console.log(
//           '--------------------------------------------------'
//         );
//       }
//     }


//     // --------------------------------------------------------
//     // Summary
//     // --------------------------------------------------------

//     console.log('\n');
//     console.log('==================================================');
//     console.log('                UPDATE SUMMARY');
//     console.log('==================================================');

//     console.log(
//       `Questions checked       : ${questions.length}`
//     );

//     console.log(
//       `Questions to update     : ${questionsToUpdate}`
//     );

//     console.log(
//       `Domains to standardize  : ${domainsToUpdate}`
//     );

//     console.log(
//       `MongoDB operations      : ${operations.length}`
//     );


//     if (operations.length === 0) {
//       console.log(
//         '\n✅ No questions require an update.'
//       );

//       return;
//     }


//     // ========================================================
//     // DRY RUN
//     // ========================================================

//     if (!PERFORM_UPDATE) {
//       console.log('\n⚠️ DRY RUN MODE');
//       console.log(
//         'No changes were made to MongoDB.'
//       );

//       console.log(
//         '\nSet PERFORM_UPDATE = true to actually update.'
//       );

//       return;
//     }


//     // ========================================================
//     // PERFORM UPDATE
//     // ========================================================

//     console.log('\n🚨 Performing MongoDB update...');

//     const result =
//       await questionsCollection.bulkWrite(
//         operations,
//         {
//           ordered: false,
//         }
//       );


//     // ========================================================
//     // RESULT
//     // ========================================================

//     console.log('\n');
//     console.log('==================================================');
//     console.log('              UPDATE COMPLETED');
//     console.log('==================================================');

//     console.log(
//       `Matched documents : ${result.matchedCount}`
//     );

//     console.log(
//       `Modified documents: ${result.modifiedCount}`
//     );

//     console.log('\n✅ Domain normalization completed successfully.');
//   } catch (error) {
//     console.error(
//       '\n🔴 Error updating question domains:',
//       error
//     );
//   } finally {
//     await client.close();

//     console.log(
//       '\n🔌 Disconnected from MongoDB.'
//     );
//   }
// }


// // ============================================================
// // RUN
// // ============================================================

// updateQuestionDomains();





// import 'dotenv/config';
// import { MongoClient } from 'mongodb';
// import fs from 'fs';
// import path from 'path';
// import { fileURLToPath } from 'url';

// // ============================================================
// // CONFIGURATION
// // ============================================================

// const MONGO_URI = process.env.DB_URL || '';
// const DB_NAME = process.env.DB_NAME || 'agriai';

// const QUESTIONS_COLLECTION = 'questions';

// // Report generated by normalise-domain.js
// const __filename = fileURLToPath(import.meta.url);
// const __dirname = path.dirname(__filename);

// const REPORT_FILE_PATH = path.join(
//   __dirname,
//   '..',
//   'domain-diff-report.json'
// );

// // ============================================================
// // SAFETY / PERFORMANCE SETTINGS
// // ============================================================

// // Number of questions processed at a time
// const BATCH_SIZE = 500;

// // false = dry run, no MongoDB changes
// // true  = actually update MongoDB
// const PERFORM_UPDATE = true;


// // ============================================================
// // VALIDATION
// // ============================================================

// if (!MONGO_URI) {
//   throw new Error(
//     '❌ DB_URL is not defined in the environment.'
//   );
// }


// // ============================================================
// // HELPERS
// // ============================================================

// function normalizeDomain(domain) {
//   return String(domain || '')
//     .trim()
//     .replace(/\s+/g, ' ')
//     .toLowerCase();
// }


// // ============================================================
// // LOAD VERIFIED MAPPINGS
// // ============================================================

// function loadDomainReport() {
//   console.log('📖 Reading domain diff report...');

//   if (!fs.existsSync(REPORT_FILE_PATH)) {
//     throw new Error(
//       `❌ Report file not found:\n${REPORT_FILE_PATH}`
//     );
//   }

//   const report = JSON.parse(
//     fs.readFileSync(REPORT_FILE_PATH, 'utf8')
//   );

//   if (!Array.isArray(report.mappedDomains)) {
//     throw new Error(
//       '❌ mappedDomains not found in domain-diff-report.json'
//     );
//   }

//   console.log(
//     `✅ Loaded ${report.mappedDomains.length} verified mappings.\n`
//   );

//   return report;
// }


// // ============================================================
// // BUILD MAPPING
// // ============================================================

// function buildMapping(mappedDomains) {
//   const mapping = new Map();

//   for (const item of mappedDomains) {
//     if (
//       !item.originalDomain ||
//       !item.standardizedDomain
//     ) {
//       continue;
//     }

//     const originalKey = normalizeDomain(
//       item.originalDomain
//     );

//     mapping.set(
//       originalKey,
//       item.standardizedDomain
//     );
//   }

//   return mapping;
// }


// // ============================================================
// // UPDATE QUESTIONS
// // ============================================================

// async function updateQuestionDomains() {
//   const client = new MongoClient(MONGO_URI);

//   try {
//     // --------------------------------------------------------
//     // Load mappings
//     // --------------------------------------------------------

//     const report = loadDomainReport();

//     const domainMapping = buildMapping(
//       report.mappedDomains
//     );

//     if (domainMapping.size === 0) {
//       console.log(
//         '⚠️ No mapped domains available for update.'
//       );

//       return;
//     }

//     console.log('Mappings that will be used:\n');

//     for (const [original, standardized] of domainMapping) {
//       console.log(
//         `  ${original} -> ${standardized}`
//       );
//     }

//     console.log('\n');


//     // --------------------------------------------------------
//     // Connect
//     // --------------------------------------------------------

//     console.log('🚀 Connecting to MongoDB...');

//     await client.connect();

//     console.log(
//       '✅ Connected to MongoDB successfully.\n'
//     );

//     const db = client.db(DB_NAME);

//     const questionsCollection = db.collection(
//       QUESTIONS_COLLECTION
//     );


//     // --------------------------------------------------------
//     // Count questions
//     // --------------------------------------------------------

//     const totalQuestions =
//       await questionsCollection.countDocuments({
//         'details.domain': {
//           $type: 'array',
//         },
//       });

//     console.log(
//       `🔍 Total questions to check: ${totalQuestions}`
//     );

//     console.log(
//       `📦 Batch size: ${BATCH_SIZE}`
//     );

//     console.log(
//       `🔧 Mode: ${
//         PERFORM_UPDATE
//           ? 'LIVE UPDATE'
//           : 'DRY RUN'
//       }\n`
//     );


//     // --------------------------------------------------------
//     // Counters
//     // --------------------------------------------------------

//     let processedQuestions = 0;
//     let questionsToUpdate = 0;
//     let domainsToStandardize = 0;
//     let modifiedDocuments = 0;

//     let batchNumber = 0;


//     // ========================================================
//     // PROCESS IN BATCHES
//     // ========================================================

//     while (processedQuestions < totalQuestions) {
//       batchNumber++;

//       console.log(
//         `\n==================================================`
//       );

//       console.log(
//         `BATCH ${batchNumber}`
//       );

//       console.log(
//         `==================================================`
//       );


//       // ------------------------------------------------------
//       // Fetch one batch
//       // ------------------------------------------------------

//       const questions =
//         await questionsCollection
//           .find(
//             {
//               'details.domain': {
//                 $type: 'array',
//               },
//             },
//             {
//               projection: {
//                 _id: 1,
//                 'details.domain': 1,
//               },
//             }
//           )
//           .sort({
//             _id: 1,
//           })
//           .skip(processedQuestions)
//           .limit(BATCH_SIZE)
//           .toArray();


//       if (questions.length === 0) {
//         break;
//       }


//       // ------------------------------------------------------
//       // Prepare operations for this batch only
//       // ------------------------------------------------------

//       const operations = [];

//       let batchQuestionsToUpdate = 0;
//       let batchDomainsToStandardize = 0;


//       for (const question of questions) {
//         const domains = question?.details?.domain;

//         if (!Array.isArray(domains)) {
//           continue;
//         }

//         let hasChanges = false;
//         let changedCount = 0;


//         // ----------------------------------------------------
//         // Replace mapped domains
//         // ----------------------------------------------------

//         const updatedDomains = domains.map(
//           domain => {
//             const normalized =
//               normalizeDomain(domain);

//             const standardized =
//               domainMapping.get(normalized);

//             if (standardized) {
//               hasChanges = true;
//               changedCount++;

//               return standardized;
//             }

//             return domain;
//           }
//         );


//         // ----------------------------------------------------
//         // Remove duplicate domains
//         // ----------------------------------------------------

//         const uniqueDomains = [
//           ...new Map(
//             updatedDomains.map(domain => [
//               normalizeDomain(domain),
//               domain,
//             ])
//           ).values(),
//         ];


//         // ----------------------------------------------------
//         // Check if array actually changed
//         // ----------------------------------------------------

//         const domainsChanged =
//           hasChanges ||
//           uniqueDomains.length !== domains.length;


//         if (!domainsChanged) {
//           continue;
//         }


//         batchQuestionsToUpdate++;
//         batchDomainsToStandardize += changedCount;


//         // ----------------------------------------------------
//         // Add update operation
//         // ----------------------------------------------------

//         operations.push({
//           updateOne: {
//             filter: {
//               _id: question._id,

//               // Safety condition:
//               // Only update if the document still contains
//               // one of the original mapped domains.
//               'details.domain': {
//                 $in: [...domainMapping.keys()],
//               },
//             },

//             update: {
//               $set: {
//                 'details.domain': uniqueDomains,
//               },
//             },
//           },
//         });


//         // ----------------------------------------------------
//         // Show first few changes of each batch
//         // ----------------------------------------------------

//         if (
//           batchQuestionsToUpdate <= 5
//         ) {
//           console.log(
//             `\nQuestion: ${question._id}`
//           );

//           console.log(
//             `  OLD: ${JSON.stringify(domains)}`
//           );

//           console.log(
//             `  NEW: ${JSON.stringify(uniqueDomains)}`
//           );
//         }
//       }


//       // ------------------------------------------------------
//       // Batch statistics
//       // ------------------------------------------------------

//       console.log(
//         `\nQuestions in batch       : ${questions.length}`
//       );

//       console.log(
//         `Questions to update      : ${batchQuestionsToUpdate}`
//       );

//       console.log(
//         `Domains to standardize   : ${batchDomainsToStandardize}`
//       );

//       console.log(
//         `MongoDB operations       : ${operations.length}`
//       );


//       // ------------------------------------------------------
//       // Perform batch update
//       // ------------------------------------------------------

//       if (
//         PERFORM_UPDATE &&
//         operations.length > 0
//       ) {
//         console.log(
//           '\n🚀 Updating batch...'
//         );

//         const result =
//           await questionsCollection.bulkWrite(
//             operations,
//             {
//               ordered: false,
//             }
//           );

//         modifiedDocuments +=
//           result.modifiedCount;

//         console.log(
//           `✅ Modified: ${result.modifiedCount}`
//         );
//       } else if (
//         !PERFORM_UPDATE &&
//         operations.length > 0
//       ) {
//         console.log(
//           '⚠️ DRY RUN - no database changes made.'
//         );
//       }


//       // ------------------------------------------------------
//       // Update global counters
//       // ------------------------------------------------------

//       processedQuestions += questions.length;

//       questionsToUpdate +=
//         batchQuestionsToUpdate;

//       domainsToStandardize +=
//         batchDomainsToStandardize;


//       // ------------------------------------------------------
//       // Progress
//       // ------------------------------------------------------

//       const percentage =
//         (
//           (processedQuestions /
//             totalQuestions) *
//           100
//         ).toFixed(2);

//       console.log(
//         `\n📊 Progress: ${processedQuestions}/${totalQuestions} (${percentage}%)`
//       );

//       console.log(
//         `📊 Total questions requiring update so far: ${questionsToUpdate}`
//       );
//     }


//     // ========================================================
//     // FINAL SUMMARY
//     // ========================================================

//     console.log('\n');

//     console.log(
//       '=================================================='
//     );

//     console.log(
//       '              FINAL UPDATE SUMMARY'
//     );

//     console.log(
//       '=================================================='
//     );

//     console.log(
//       `Questions checked       : ${processedQuestions}`
//     );

//     console.log(
//       `Questions to update     : ${questionsToUpdate}`
//     );

//     console.log(
//       `Domains to standardize  : ${domainsToStandardize}`
//     );

//     if (PERFORM_UPDATE) {
//       console.log(
//         `Documents modified     : ${modifiedDocuments}`
//       );

//       console.log(
//         '\n✅ Domain normalization completed.'
//       );
//     } else {
//       console.log(
//         '\n⚠️ DRY RUN MODE'
//       );

//       console.log(
//         'No changes were made to MongoDB.'
//       );

//       console.log(
//         '\nSet PERFORM_UPDATE = true to actually update.'
//       );
//     }
//   } catch (error) {
//     console.error(
//       '\n🔴 Error updating question domains:',
//       error
//     );
//   } finally {
//     await client.close();

//     console.log(
//       '\n🔌 Disconnected from MongoDB.'
//     );
//   }
// }


// // ============================================================
// // RUN
// // ============================================================

// updateQuestionDomains();



import 'dotenv/config';
import { MongoClient } from 'mongodb';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// ============================================================
// CONFIGURATION
// ============================================================

const MONGO_URI = process.env.DB_URL || '';
const DB_NAME = process.env.DB_NAME || 'agriai';

const QUESTIONS_COLLECTION = 'questions';

// ============================================================
// FILE PATH
// ============================================================

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const REPORT_FILE_PATH = path.join(
  __dirname,
  '..',
  'domain-diff-report.json'
);

// ============================================================
// SETTINGS
// ============================================================

// Number of questions processed in one batch
const BATCH_SIZE = 500;

// false = dry run
// true  = actually update MongoDB
const PERFORM_UPDATE = true;

// Number of example changes to print per batch
const EXAMPLES_PER_BATCH = 5;


// ============================================================
// VALIDATION
// ============================================================

if (!MONGO_URI) {
  throw new Error(
    '❌ DB_URL is not defined in the environment.'
  );
}


// ============================================================
// NORMALIZE DOMAIN
// ============================================================

function normalizeDomain(domain) {
  return String(domain || '')
    .trim()
    .replace(/\s+/g, ' ')
    .toLowerCase();
}


// ============================================================
// LOAD DOMAIN REPORT
// ============================================================

function loadDomainReport() {
  console.log('📖 Reading domain diff report...');

  if (!fs.existsSync(REPORT_FILE_PATH)) {
    throw new Error(
      `❌ Report file not found:\n${REPORT_FILE_PATH}`
    );
  }

  const report = JSON.parse(
    fs.readFileSync(REPORT_FILE_PATH, 'utf8')
  );

  if (!Array.isArray(report.mappedDomains)) {
    throw new Error(
      '❌ mappedDomains not found in domain-diff-report.json'
    );
  }

  console.log(
    `✅ Loaded ${report.mappedDomains.length} verified mappings.\n`
  );

  return report;
}


// ============================================================
// BUILD DOMAIN MAPPING
// ============================================================

function buildMapping(mappedDomains) {
  const mapping = new Map();

  for (const item of mappedDomains) {
    if (
      !item?.originalDomain ||
      !item?.standardizedDomain
    ) {
      continue;
    }

    const originalKey = normalizeDomain(
      item.originalDomain
    );

    const standardizedDomain =
      String(item.standardizedDomain).trim();

    // Prevent accidental self-mapping
    if (
      originalKey === normalizeDomain(
        standardizedDomain
      )
    ) {
      continue;
    }

    mapping.set(
      originalKey,
      standardizedDomain
    );
  }

  return mapping;
}


// ============================================================
// UPDATE QUESTION DOMAINS
// ============================================================

async function updateQuestionDomains() {
  const client = new MongoClient(MONGO_URI);

  try {
    // --------------------------------------------------------
    // Load verified mappings
    // --------------------------------------------------------

    const report = loadDomainReport();

    const domainMapping = buildMapping(
      report.mappedDomains
    );

    if (domainMapping.size === 0) {
      console.log(
        '⚠️ No mapped domains available for update.'
      );

      return;
    }

    console.log(
      '🔄 Mappings that will be used:\n'
    );

    for (
      const [original, standardized]
      of domainMapping
    ) {
      console.log(
        `  ${original} -> ${standardized}`
      );
    }

    console.log('\n');


    // --------------------------------------------------------
    // Connect to MongoDB
    // --------------------------------------------------------

    console.log(
      '🚀 Connecting to MongoDB...'
    );

    await client.connect();

    console.log(
      '✅ Connected to MongoDB successfully.\n'
    );

    const db = client.db(DB_NAME);

    const questionsCollection =
      db.collection(
        QUESTIONS_COLLECTION
      );


    // --------------------------------------------------------
    // Count questions
    // --------------------------------------------------------

    const totalQuestions =
      await questionsCollection.countDocuments({
        'details.domain': {
          $type: 'array',
        },
      });

    console.log(
      `🔍 Total questions to check: ${totalQuestions}`
    );

    console.log(
      `📦 Batch size: ${BATCH_SIZE}`
    );

    console.log(
      `🔧 Mode: ${
        PERFORM_UPDATE
          ? 'LIVE UPDATE'
          : 'DRY RUN'
      }\n`
    );


    // --------------------------------------------------------
    // Counters
    // --------------------------------------------------------

    let processedQuestions = 0;
    let questionsToUpdate = 0;
    let domainsToStandardize = 0;
    let modifiedDocuments = 0;

    let batchNumber = 0;

    // Cursor pagination
    let lastId = null;


    // ========================================================
    // PROCESS BATCHES
    // ========================================================

    while (true) {
      batchNumber++;

      console.log(
        '\n=================================================='
      );

      console.log(
        `BATCH ${batchNumber}`
      );

      console.log(
        '=================================================='
      );


      // ------------------------------------------------------
      // Build batch query
      // ------------------------------------------------------

      const query = {
        'details.domain': {
          $type: 'array',
        },
      };

      // Use _id cursor instead of skip()
      if (lastId) {
        query._id = {
          $gt: lastId,
        };
      }


      // ------------------------------------------------------
      // Fetch batch
      // ------------------------------------------------------

      const questions =
        await questionsCollection
          .find(
            query,
            {
              projection: {
                _id: 1,
                'details.domain': 1,
              },
            }
          )
          .sort({
            _id: 1,
          })
          .limit(BATCH_SIZE)
          .toArray();


      // ------------------------------------------------------
      // Nothing left
      // ------------------------------------------------------

      if (questions.length === 0) {
        break;
      }


      // ------------------------------------------------------
      // Prepare batch operations
      // ------------------------------------------------------

      const operations = [];

      let batchQuestionsToUpdate = 0;
      let batchDomainsToStandardize = 0;

      let examplesPrinted = 0;


      // ======================================================
      // PROCESS QUESTIONS IN THIS BATCH
      // ======================================================

      for (const question of questions) {
        const domains =
          question?.details?.domain;

        if (!Array.isArray(domains)) {
          continue;
        }


        let hasMappedDomain = false;
        let changedCount = 0;


        // ----------------------------------------------------
        // Replace mapped domains
        // ----------------------------------------------------

        const updatedDomains =
          domains.map(domain => {
            const normalized =
              normalizeDomain(domain);

            const standardized =
              domainMapping.get(
                normalized
              );

            if (standardized) {
              hasMappedDomain = true;
              changedCount++;

              return standardized;
            }

            return domain;
          });


        // ----------------------------------------------------
        // Remove duplicates
        //
        // Example:
        //
        // [
        //   "Soil Health Card",
        //   "Soil Health and Nutrient Management"
        // ]
        //
        // becomes:
        //
        // [
        //   "Soil Health and Nutrient Management"
        // ]
        // ----------------------------------------------------

        const uniqueDomains = [
          ...new Map(
            updatedDomains.map(domain => [
              normalizeDomain(domain),
              domain,
            ])
          ).values(),
        ];


        // ----------------------------------------------------
        // Determine whether update is required
        // ----------------------------------------------------

        const domainsChanged =
          hasMappedDomain ||
          uniqueDomains.length !==
            domains.length;

        if (!domainsChanged) {
          continue;
        }


        batchQuestionsToUpdate++;

        batchDomainsToStandardize +=
          changedCount;


        // ----------------------------------------------------
        // Add update operation
        //
        // IMPORTANT:
        // Only _id is used here.
        //
        // We already inspected this exact document and
        // generated the new domain array.
        // ----------------------------------------------------

        operations.push({
          updateOne: {
            filter: {
              _id: question._id,
            },

            update: {
              $set: {
                'details.domain':
                  uniqueDomains,
              },
            },
          },
        });


        // ----------------------------------------------------
        // Print examples
        // ----------------------------------------------------

        if (
          examplesPrinted <
          EXAMPLES_PER_BATCH
        ) {
          console.log(
            `\nQuestion: ${question._id}`
          );

          console.log(
            `  OLD: ${JSON.stringify(domains)}`
          );

          console.log(
            `  NEW: ${JSON.stringify(uniqueDomains)}`
          );

          console.log(
            '--------------------------------------------------'
          );

          examplesPrinted++;
        }
      }


      // ======================================================
      // BATCH SUMMARY
      // ======================================================

      console.log(
        `\nQuestions in batch       : ${questions.length}`
      );

      console.log(
        `Questions to update      : ${batchQuestionsToUpdate}`
      );

      console.log(
        `Domains to standardize   : ${batchDomainsToStandardize}`
      );

      console.log(
        `MongoDB operations       : ${operations.length}`
      );


      // ======================================================
      // PERFORM BATCH UPDATE
      // ======================================================

      if (
        PERFORM_UPDATE &&
        operations.length > 0
      ) {
        console.log(
          '\n🚀 Updating batch...'
        );

        const result =
          await questionsCollection.bulkWrite(
            operations,
            {
              ordered: false,
            }
          );

        modifiedDocuments +=
          result.modifiedCount;

        console.log(
          `✅ Matched: ${result.matchedCount}`
        );

        console.log(
          `✅ Modified: ${result.modifiedCount}`
        );
      }

      // ------------------------------------------------------
      // Dry run
      // ------------------------------------------------------

      else if (
        !PERFORM_UPDATE &&
        operations.length > 0
      ) {
        console.log(
          '⚠️ DRY RUN - no database changes made.'
        );
      }


      // ======================================================
      // UPDATE GLOBAL COUNTERS
      // ======================================================

      processedQuestions +=
        questions.length;

      questionsToUpdate +=
        batchQuestionsToUpdate;

      domainsToStandardize +=
        batchDomainsToStandardize;


      // ------------------------------------------------------
      // Set cursor for next batch
      // ------------------------------------------------------

      lastId =
        questions[questions.length - 1]._id;


      // ======================================================
      // PROGRESS
      // ======================================================

      const percentage =
        totalQuestions === 0
          ? 100
          : (
              (processedQuestions /
                totalQuestions) *
              100
            ).toFixed(2);

      console.log(
        `\n📊 Progress: ${processedQuestions}/${totalQuestions} (${percentage}%)`
      );

      console.log(
        `📊 Questions requiring update so far: ${questionsToUpdate}`
      );
    }


    // ========================================================
    // FINAL SUMMARY
    // ========================================================

    console.log('\n');

    console.log(
      '=================================================='
    );

    console.log(
      '              FINAL UPDATE SUMMARY'
    );

    console.log(
      '=================================================='
    );

    console.log(
      `Questions checked       : ${processedQuestions}`
    );

    console.log(
      `Questions to update     : ${questionsToUpdate}`
    );

    console.log(
      `Domains to standardize  : ${domainsToStandardize}`
    );


    if (PERFORM_UPDATE) {
      console.log(
        `Documents modified     : ${modifiedDocuments}`
      );

      console.log(
        '\n✅ Domain normalization completed successfully.'
      );
    } else {
      console.log(
        '\n⚠️ DRY RUN MODE'
      );

      console.log(
        'No changes were made to MongoDB.'
      );

      console.log(
        '\nSet PERFORM_UPDATE = true to actually update.'
      );
    }
  } catch (error) {
    console.error(
      '\n🔴 Error updating question domains:',
      error
    );
  } finally {
    await client.close();

    console.log(
      '\n🔌 Disconnected from MongoDB.'
    );
  }
}


// ============================================================
// RUN
// ============================================================

updateQuestionDomains();