runtime: nodejs22

instance_class: B4_1

manual_scaling:
  instances: 1

env_variables:
  NODE_ENV: "staging"
  APP_PORT: "4001"
  APP_ROUTE_PREFIX: "/api"
  APP_ORIGINS: "*"
  
  # Database
  DB_URL: "REPLACE_ME"
  DB_NAME: "REPLACE_ME"
  
  # Firebase Admin
  FIREBASE_PROJECT_ID: "REPLACE_ME"
  FIREBASE_CLIENT_EMAIL: "REPLACE_ME"
  FIREBASE_PRIVATE_KEY: "REPLACE_ME"

  # Plivo
  PLIVO_AUTH_ID: "REPLACE_ME"
  PLIVO_AUTH_TOKEN: "REPLACE_ME"
  PLIVO_NUMBER: "REPLACE_ME"
  PLIVO_STREAM_URL: "REPLACE_ME"
  PLIVO_ENDPOINT_USERNAME_AGENT_1: "REPLACE_ME"
  PLIVO_ENDPOINT_USERNAME_AGENT_2: "REPLACE_ME"
  PLIVO_ENDPOINT_USERNAME_AGENT_3: "REPLACE_ME"
  PLIVO_ENDPOINT_USERNAME_AGENT_4: "REPLACE_ME"

  # AI Agent
  ACC_AGENT_BASE_URL: "REPLACE_ME"
  ACC_AGENT_ASSISTANT_ID: "REPLACE_ME"
  ACC_AGENT_TIMEOUT: "120000"

  # Sarvam & SMS
  SARVAM_API_KEY: "REPLACE_ME"
  FAST2SMS_API_KEY: "REPLACE_ME"

network:
  session_affinity: true