# Auto-generated by reviewer_mcp.py on 2026-02-19T09:12:29.572428+05:30

state_crops_reviewer_dataset = {
    "": [
        ""
    ],
    "Arunachal Pradesh": [
        "paddy"
    ],
    "Bihar": [
        "maize"
    ],
    "Chandigarh": [
        "Carrot",
        "Onion"
    ],
    "Delhi": [
        "Not specified",
        "Paddy",
        "Potato",
        "potato"
    ],
    "Gujarat": [
        "groundnut"
    ],
    "Haryana": [
        "Paddy",
        "Wheat"
    ],
    "Himachal Pradesh": [
        "Unknown",
        "Wheat",
        "apple"
    ],
    "Karnataka": [
        "Bengal gram",
        "Drumstick",
        "General",
        "Paddy",
        "Ragi",
        "Sugarcane",
        "Unknown",
        "Wheat"
    ],
    "Madhya Pradesh": [
        "Barley Jau",
        "Coriander",
        "Onion",
        "Rice",
        "Tomato",
        "Wheat",
        "soybean"
    ],
    "Maharashtra": [
        "Gram",
        "Onion",
        "Wheat",
        "cotton",
        "sugarcane"
    ],
    "N/A": [
        "N/A"
    ],
    "Not specified": [
        "Not specified",
        "Paddy",
        "Potato",
        "potato"
    ],
    "Odisha": [
        "Wheat"
    ],
    "Punjab": [
        "Almond/Apple",
        "Bajra (Pearl Millet)",
        "Barley",
        "Barley Jau",
        "Basmati",
        "Basmati Paddy",
        "Basmati Rice",
        "Bengal Gram GramChick PeaKabuliChana",
        "Berseem",
        "Black Cumin (Kalonji)",
        "Black Gram",
        "Brown Sarson",
        "Buffalo",
        "Buffalo/Cattle",
        "Carrots",
        "Cattle",
        "Cauliflower",
        "Cauliflower and Mustard",
        "Chilli",
        "Coconut",
        "Cotton",
        "Cow/Buffalo",
        "Cow/Cattle",
        "Crop Production",
        "Cumin",
        "Dairy Cattle",
        "Dairy Cattle/Buffalo",
        "Dairy Cow",
        "Fodder Maize",
        "Fruit Trees",
        "Garlic",
        "Garlic and Onion",
        "General",
        "General Crops",
        "General crop selection",
        "General crops",
        "Groundnut",
        "Guava",
        "Indian rapeseed and mustard yellow sarson",
        "Lentil Masur",
        "Linseed alsi",
        "Livestock",
        "Maize",
        "Maize/Fodder",
        "Mango",
        "Mustard",
        "Not specified",
        "Oats",
        "Onion",
        "Paddy",
        "Poplar",
        "Poplar (Agroforestry)",
        "Potato",
        "Potatoes",
        "Pulses",
        "Rice",
        "Sugarcane",
        "Summer Vegetables",
        "Tomato",
        "Toria",
        "Turmeric",
        "Unknown",
        "Vegetables",
        "Weather",
        "Wheat",
        "potatoes",
        "sugarcane",
        "sweet potato",
        "sweetpotato",
        "turmeric",
        "\u0a27\u0a3e\u0a28"
    ],
    "Rajasthan": [
        "General",
        "Onion"
    ],
    "Tamil Nadu": [
        "Paddy",
        "Wheat",
        "paddy"
    ],
    "Telangana": [
        "Paddy"
    ],
    "UTTAR PRADESH": [
        "Paddy",
        "Paddy (Dhan)"
    ],
    "Unknown": [
        "General",
        "Paddy",
        "Ragi",
        "Unknown",
        "Wheat"
    ],
    "Uttar Pradesh": [
        "Bhindi",
        "General Query",
        "GramChick",
        "N/A",
        "Paddy",
        "Potato",
        "Rice",
        "WHEAT",
        "Wheat",
        "bhindi",
        "paddy",
        "potato",
        "rice",
        "sugarcane",
        "wheat"
    ],
    "Uttarakhand": [
        "Paddy"
    ],
    "West Bengal": [
        "Brown Sarson",
        "Chilli",
        "Indian rapeseed and mustard yellow sarson",
        "Mustard",
        "Potato",
        "Raya Indian Mustard",
        "paddy"
    ],
    "unknown": [
        "unknown"
    ],
    "\u0a2a\u0a70\u0a1c\u0a3e\u0a2c": [
        "\u0a1d\u0a4b\u0a28\u0a47"
    ]
}

reviewer_state_codes = {
    "ARUNACHAL PRADESH": "Arunachal Pradesh",
    "BIHAR": "Bihar",
    "CHANDIGARH": "Chandigarh",
    "DELHI": "Delhi",
    "GUJARAT": "Gujarat",
    "HARYANA": "Haryana",
    "HIMACHAL PRADESH": "Himachal Pradesh",
    "KARNATAKA": "Karnataka",
    "MADHYA PRADESH": "Madhya Pradesh",
    "MAHARASHTRA": "Maharashtra",
    "N/A": "N/A",
    "NOT SPECIFIED": "Not specified",
    "ODISHA": "Odisha",
    "PUNJAB": "Punjab",
    "RAJASTHAN": "Rajasthan",
    "TAMIL NADU": "Tamil Nadu",
    "TELANGANA": "Telangana",
    "UTTAR PRADESH": "Uttar Pradesh",
    "UNKNOWN": "unknown",
    "UTTARAKHAND": "Uttarakhand",
    "WEST BENGAL": "West Bengal",
    "\u0a2a\u0a70\u0a1c\u0a3e\u0a2c": "\u0a2a\u0a70\u0a1c\u0a3e\u0a2c"
}

last_updated_metadata = "2026-02-19T09:12:29.572428+05:30"
