import os
import json
import datetime
import importlib
import asyncio
from typing import List, Optional

from fastmcp import FastMCP
from motor.motor_asyncio import AsyncIOMotorClient
from domains import allowed_domains, crop_required_domains, crop_all_domains
# Local imports
import reviewer_values
# We import the tool function directly. Note that it's an async function decorated with @tool.
# FastMCP can wrap it, or we can call it directly. 
# Since we need to match the signature requested by the user, we will wrap it.
from reviewer_rag_tool import reviewer_retriever_tool
from context_validator import validate_retrieved_context
from reviewer_exact_match import find_exact_question_context

ALLOWED_DOMAINS_DOC = ", ".join(sorted(allowed_domains))

# Initialize FastMCP
mcp = FastMCP("Reviewer_MCP")

# Environment Variables
REVIEWER_MONGODB_URI = os.getenv("REVIEWER_MONGODB_URI")
REVIEWER_MONGODB_DATABASE = os.getenv("REVIEWER_MONGODB_DATABASE")
REVIEWER_MONGODB_COLLECTION = os.getenv("REVIEWER_MONGODB_COLLECTION") # Questions collection

# --- Helper Functions for Reviewer Data Update ---

async def update_reviewer_data():
    """
    Checks if reviewer_values.py needs an update (older than 24h).
    If so, fetches new data from MongoDB, rewrites reviewer_values.py, and reloads the module.
    """
    print("Checking for Reviewer Data updates...")
    
    # Check last update time
    last_updated_str = getattr(reviewer_values, "last_updated_metadata", "2000-01-01T00:00:00")
    try:
        last_updated = datetime.datetime.fromisoformat(last_updated_str)
    except ValueError:
        last_updated = datetime.datetime(2000, 1, 1)

    # Use IST for consistency
    ist_timezone = datetime.timezone(datetime.timedelta(hours=5, minutes=30))
    today_ist = datetime.datetime.now(ist_timezone)
    
    if last_updated.tzinfo is None:
         last_updated = last_updated.replace(tzinfo=ist_timezone)

    if (today_ist - last_updated) < datetime.timedelta(hours=6):
        print("Reviewer Data is up-to-date. Skipping update.")
        return

    print("Reviewer Data is stale. Fetching from MongoDB...")

    try:
        if not REVIEWER_MONGODB_URI or not REVIEWER_MONGODB_DATABASE:
            print("Error: Missing MongoDB credentials in env.")
            return

        mongo_client = AsyncIOMotorClient(REVIEWER_MONGODB_URI, serverSelectionTimeoutMS=5000)
        database = mongo_client[REVIEWER_MONGODB_DATABASE]
        questions_collection = database[REVIEWER_MONGODB_COLLECTION]

        # 1. Fetch State Crops Mapping
        pipeline = [
            {
                "$match": {
                    "details.state": {"$exists": True, "$ne": None},
                    "details.crop": {"$exists": True, "$ne": None},
                }
            },
            {
                "$group": {
                    "_id": "$details.state",
                    "crops": {"$addToSet": "$details.crop"}
                }
            },
            {"$sort": {"_id": 1}}
        ]
        
        cursor = questions_collection.aggregate(pipeline)
        state_crops_reviewer_dataset = {}
        async for doc in cursor:
            state_key = doc["_id"]
            state_crops_reviewer_dataset[state_key] = sorted(list(doc["crops"]))
        
        # 2. Get distinct states for the codes mapping
        distinct_states = await questions_collection.distinct("details.state", {"details.state": {"$exists": True, "$ne": None}})
        
        reviewer_state_codes = {}
        for s in distinct_states:
            if s:
                reviewer_state_codes[s.upper()] = s

        # 3. Rewrite reviewer_values.py
        new_timestamp = datetime.datetime.now(ist_timezone).isoformat()
        
        content = f"# Auto-generated by reviewer_mcp.py on {new_timestamp}\n\n"
        content += f"state_crops_reviewer_dataset = {json.dumps(state_crops_reviewer_dataset, indent=4)}\n\n"
        content += f"reviewer_state_codes = {json.dumps(reviewer_state_codes, indent=4)}\n\n"
        content += f"last_updated_metadata = \"{new_timestamp}\"\n"

        current_dir = os.path.dirname(os.path.abspath(__file__))
        values_file = os.path.join(current_dir, 'reviewer_values.py')
        
        with open(values_file, 'w') as f:
            f.write(content)
            
        print("reviewer_values.py updated successfully.")

        # 4. Hot Reload
        importlib.reload(reviewer_values)
        print("reviewer_values module reloaded with new data.")

    except Exception as e:
        print(f"Error updating reviewer data: {e}")
        import traceback
        traceback.print_exc()


# --- MCP Tools ---

def _chunk_to_dict(chunk):
    if hasattr(chunk, "model_dump"):
        return chunk.model_dump()
    if isinstance(chunk, dict):
        return chunk
    return {"question_text": str(chunk), "question_id": None}


def _chunk_key(chunk):
    data = _chunk_to_dict(chunk)
    return (data.get("question_id"), data.get("question_text", ""))


def _chunk_question_text(chunk):
    data = _chunk_to_dict(chunk)
    return data.get("question_text", "")


def _build_final_response_text(has_relevant_data: bool) -> str:
    if has_relevant_data:
        return (
            "Retrieved data from database using similarity search. "
            "Use only answer and source_name that are relevant to the query."
        )
    return (
        "No relevant data found in reviewer database. "
        "Call golden mcp and pop mcp tool."
    )



import requests

@mcp.tool()
async def upload_question_to_reviewer_system(
    question: str,
    original_question: str,
    state: str,
    crop: str,
    domain: str,
    district: Optional[str] = None,
    season: str | None = None,
) -> dict:
    """
    This is the first tool that must be called before calling any other tool.
    Upload the question to the reviewer system for further review by human experts.
    Parameters:
    - original_question (str): The exact, unmodified query as provided by the user.
                               This should include the raw user input before any preprocessing, translation,
                               normalization, or interpretation by the system. It helps human experts understand
                               the original context, phrasing, and intent of the user.
    - question (str): The question that needs to be reviewed by human experts. 
                      This should be a string containing the query related to crop protection or any other agricultural query.
    - state (str): The full state name (e.g., "Punjab").
    - district (str, optional): The district name (e.g., "Chandigarh"). Defaults to "Not specified".
    - crop (str): The type of crop associated with the query. This will be a string like "Paddy" or other crop names.
                  Ask farmer about the crop if domain is in this list: Agriculture Mechanization, Bio-Pesticides and Bio-Fertilizers, Crop Insurance, Cultural Practices, Fertilizer Use and Availability, Field Preparation, Horticulture & Allied Agriculture, Market Information, Nutrient Management, Organic Farming, Plant Protection, Post Harvest Preservation, Seeds, Soil Testing, Sowing Time and Weather, Storage, Varieties, Water Management, Weed Management.
                  If domain is in this list, crop will be auto-set to "all": Extension & Capacity Building, Financial & Institutional Services, Fisheries & Aquaculture, Infrastructure & Utilities, Livestock & Animal Husbandry, Soil Health Card, Veterinary & Animal Health.
    - domain (str): Must be one of allowed domains: Agriculture Mechanization, Bio-Pesticides and Bio-Fertilizers, Crop Insurance, Cultural Practices, Extension & Capacity Building, Fertilizer Use and Availability, Field Preparation, Financial & Institutional Services, Fisheries & Aquaculture, Horticulture & Allied Agriculture, Infrastructure & Utilities, Livestock & Animal Husbandry, Market Information, Nutrient Management, Organic Farming, Plant Protection, Post Harvest Preservation, Seeds, Soil Health Card, Soil Testing, Sowing Time and Weather, Storage, Varieties, Veterinary & Animal Health, Water Management, Weed Management.
    - season (str, optional): Crop season (must be one of: "Kharif", "Rabi", "Zaid", "Pre-Kharif", "Post-Kharif",
                         "Pre-Rabi", "Zaid Rabi", "Spring", "Summer", "Autumn",
                         "Winter", "Monsoon", "Dry Season", "Wet Season"). If missing, defaults to "General".
    """

    # Define constant values
    source = "AJRASAKHA"
    priority = "high"
    context = ""  # Empty string as context for now

    details = {
        "state": state,
        "district": district,
        "crop": crop,
        "season": season,
        "domain": domain,
    }

    domain_value = str(domain or "").strip()
    if domain_value and domain_value not in allowed_domains:
        return {
            "status": "Failed",
            "message": (
                f"Invalid domain '{domain_value}'. "
                f"Allowed domains: {ALLOWED_DOMAINS_DOC}"
            ),
        }

    crop_value = str(details.get("crop") or crop or "").strip()
    crop_missing = not crop_value or crop_value.lower() in {"not specified", "na", "n/a", "none", "null"}

    if domain_value in crop_required_domains and crop_missing:
        raise ValueError(
            "Crop is mandatory for this domain. Ask farmer first and do not call upload_question_to_reviewer_system until crop is provided."
        )

    if domain_value in crop_all_domains:
        details["crop"] = "all"
    elif crop_value:
        details["crop"] = crop_value

    # Ensure all required fields are non-empty
    required_fields = ["state", "district", "season", "domain"]
    for field in required_fields:
        if not details.get(field):
            if field == "district":
                details[field] = "all"
            elif field == "season":
                details[field] = "all"
            else:
                details[field] = "all"

    if not details.get("crop"):
        details["crop"] = "all"

    exact_match = await find_exact_question_context(
        mongo_uri=REVIEWER_MONGODB_URI,
        mongo_database=REVIEWER_MONGODB_DATABASE,
        mongo_collection=REVIEWER_MONGODB_COLLECTION,
        original_question=original_question or question,
        state=details.get("state"),
        crop=details.get("crop"),
    )


    # Construct the payload according to the schema
    payload = {
        "question": question,
        "originalQuestion": original_question or question,
        "priority": priority,
        "source": source,
        "details": details,
        "context": context
    }
    
    # Send the POST request
    url = "https://desk.vicharanashala.ai/api/questions"
    headers = {"Content-Type": "application/json"}

    print(f"DEBUG: Sending to URL: {url}", flush=True)
    print(f"DEBUG: Payload: {payload}", flush=True)
    try:
        response = await asyncio.to_thread(requests.post, url, json=payload, headers=headers, timeout=10)

        response_data = {}
        try:
            response_data = response.json()
        except ValueError:
            response_data = {}

        is_success = response.status_code == 201 or bool(response_data.get("success"))
        question_id = response_data.get("question_id")

        information = None
        if exact_match.get("found"):
            information = {
                "exact_question_found": True,
                "context": exact_match,
                "message": "Exact question found in reviewer database. "
                           "Respond using this context and do not call other tools.",
            }

        if is_success:
            result = {"status": "Uploaded Successfully"}
            if question_id:
                result["question_id"] = question_id
            if information:
                result["information"] = information
            return result

        failure_result = {"status": "Failed", "message": response.text}
        if information:
            failure_result["information"] = information
        return failure_result

    except requests.exceptions.RequestException as e:
        error_result = {
            "status": "Error",
            "message": str(e),
        }
        if exact_match.get("found"):
            error_result["information"] = {
                "exact_question_found": True,
                "context": exact_match,
                "message": "Exact question found in reviewer database. "
                           "Respond using this context and do not call other tools.",
                
            }
        return error_result










@mcp.tool()
async def get_context_from_reviewer_dataset(query: str, state: str = None, crop: str = None):
    """
    Retrieve the most contextually relevant agricultural question-answer pairs 
    from the Reviewer Dataset based on the query, state, and crop.
    
    This wraps the logic defined in reviewer_rag_tool.py.
    """
    await update_reviewer_data()
    
    state_to_pass = None
    
    # 1. Validate State
    if state:
        state_upper = state.upper()
        # reviewer_state_codes maps UPPER_CASE_NAME -> Original Name
        # Check if input matches a known state name (case-insensitive)
        if state_upper in reviewer_values.reviewer_state_codes:
            state_to_pass = reviewer_values.reviewer_state_codes[state_upper]
        
        else:
             # State not found. Return error with available states.
             available_states = sorted(reviewer_values.reviewer_state_codes.values())
             return f"Error: Invalid state name '{state}'. Available states are: {', '.join(available_states)}"

    
    if crop and state_to_pass:
        # Get valid crops for the state
        valid_crops = reviewer_values.state_crops_reviewer_dataset.get(state_to_pass, [])
        
        # Check case-insensitive
        crop_found = False
        for valid_crop in valid_crops:
            if valid_crop.lower() == crop.lower():
                crop = valid_crop # Canonicalize
                crop_found = True
                break
        
        if not crop_found:
            return f"Error: Invalid crop '{crop}' for state '{state_to_pass}'. Available crops are: {', '.join(valid_crops)}"

    # Trigger the underlying retriever logic.
    retrieved_chunks = await reviewer_retriever_tool.ainvoke(
        {"query": query, "crop": crop, "state": state_to_pass}
    )

    # Validate retrieved chunks against the query before passing context downstream.
    # - If validator returns None => explicit no-match condition.
    # - If validator errors => return original chunks as a safe fallback.
    try:
        validated_chunks = await validate_retrieved_context(query, retrieved_chunks)
        accepted_chunks = validated_chunks or []
        accepted_keys = {_chunk_key(chunk) for chunk in accepted_chunks}
        accepted_question_texts = [_chunk_question_text(chunk) for chunk in accepted_chunks]
        rejected_question_texts = [
            _chunk_question_text(chunk)
            for chunk in retrieved_chunks
            if _chunk_key(chunk) not in accepted_keys
        ]
        print(f"Validation Query: {query}", flush=True)
        print(f"Accepted question_text by LLM: {accepted_question_texts}", flush=True)
        print(f"Rejected question_text by LLM: {rejected_question_texts}", flush=True)
        return {
            "message": _build_final_response_text(bool(validated_chunks)),
            "data": validated_chunks,
        }
    except Exception as validation_error:
        print(f"Validation Query: {query}", flush=True)
        print("Accepted question_text by LLM: []", flush=True)
        print("Rejected question_text by LLM: []", flush=True)
        print(f"Context validator failed, returning original chunks: {validation_error}", flush=True)
        return {
            "message": _build_final_response_text(bool(retrieved_chunks)),
            "data": retrieved_chunks,
        }

@mcp.tool()
async def get_available_states_for_reviewer_dataset() -> List[dict]:
    """
    Retrieve the list of available states in the Reviewer Dataset.
    """
    await update_reviewer_data()
    return [{"state": val, "code": key} for key, val in reviewer_values.reviewer_state_codes.items()]

@mcp.tool()
async def get_crops_by_state_for_reviwer_dataset(state: str) -> List[str]:
    """
    Get the list of crops for a specific state in the Reviewer Dataset.
    """
    await update_reviewer_data()
    
    state_full = reviewer_values.reviewer_state_codes.get(state.upper(), state)
    
    crops = reviewer_values.state_crops_reviewer_dataset.get(state_full, [])
    if not crops and state in reviewer_values.state_crops_reviewer_dataset:
        crops = reviewer_values.state_crops_reviewer_dataset[state]

    return crops

if __name__ == "__main__":
    mcp.run(
        transport="streamable-http",
        host="0.0.0.0",
        port=9023,
    )
