import asyncio
import os
from dotenv import load_dotenv

# Load environment variables first
load_dotenv()

from ajrasakha.agents.acc_agent import acc_graph

scenarios = [
    {
        "id": "weather_faridabad",
        "name": "Weather Tool Scenario - Faridabad",
        "transcript": (
            "Farmer: Hello, I am calling from Faridabad, Haryana. "
            "I am planning to water my fields today. Can you tell me if there is any rain forecast for Faridabad today or tomorrow?"
        )
    },
    {
        "id": "market_maize",
        "name": "Market Price Tool Scenario - Maize in Ambala",
        "transcript": (
            "Farmer: Namaste ji. Maize price in Ambala, Haryana me kitna hai?"
        )
    }
]

async def run_scenario(scenario):
    print(f"\n{'='*60}")
    print(f"🚀 Running {scenario['name']}")
    print(f"{'='*60}\n")
    
    # Use a unique thread ID for checkpointer per scenario
    config = {"configurable": {"thread_id": f"sim-thread-{scenario['id']}"}}
    
    initial_state = {
        "transcript": scenario["transcript"]
    }
    
    print("📞 [Frontend] Received Transcript:")
    print(f'"{scenario["transcript"]}"\n')
    
    print("⏳ [Backend] Running extraction node...")
    
    # 2. Run the graph until the first interrupt (HITL pause)
    try:
        async for event in acc_graph.astream(initial_state, config=config):
            for node_name, state_update in event.items():
                print(f"✅ Finished node: {node_name}")
                if "extracted_query" in state_update:
                    print(f"  -> Query: {state_update['extracted_query']}")
                    print(f"  -> State: {state_update['extracted_state']}")
                    print(f"  -> District: {state_update['extracted_district']}")
                    print(f"  -> Crop: {state_update['extracted_crop']}")
    except Exception as e:
        print(f"Error during extraction: {e}")
        return
        
    print("\n⏸️ [Backend] Graph paused for Human-in-the-Loop verification.")
    
    paused_state = acc_graph.get_state(config)
    print("\n🧑‍💻 [Call Center Agent] Agent clicks 'Approve' (Proceeding with same values)\n")
    
    print("⏳ [Backend] Resuming graph execution (Planner -> Tool Execution -> Assembler)...")
    try:
        async for event in acc_graph.astream(None, config=config):
            for node_name, state_update in event.items():
                print(f"✅ Finished node: {node_name}")
                if "selected_tool" in state_update:
                    print(f"  -> Planner decided to use: {state_update['selected_tool']}")
                if "tool_response" in state_update:
                    print(f"  -> Received data from tool (length: {len(state_update['tool_response'])} chars)")
    except Exception as e:
        print(f"Error during execution: {e}")
        return
        
    print("\n✅ [Backend] Graph execution completed.")
    
    final_state = acc_graph.get_state(config)
    print("\n🎯 [Frontend] Final Answer generated by Assembler:")
    print("-" * 50)
    print(final_state.values.get("final_answer"))
    print("-" * 50)


async def main():
    for s in scenarios:
        await run_scenario(s)

if __name__ == "__main__":
    asyncio.run(main())
