/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappHistoryRouteImport } from './routes/whatsapp-history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PaeExpertIndexRouteImport } from './routes/pae-expert/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as GdbCoverageIndexRouteImport } from './routes/gdb-coverage/index'
import { Route as FlagsReportedIndexRouteImport } from './routes/flags-reported/index'
import { Route as CoordinatorIndexRouteImport } from './routes/coordinator/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as UserUserIdRouteImport } from './routes/user/$userId'
import { Route as CoordinatorProfileRouteImport } from './routes/coordinator/profile'

const WhatsappHistoryRoute = WhatsappHistoryRouteImport.update({
  id: '/whatsapp-history',
  path: '/whatsapp-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaeExpertIndexRoute = PaeExpertIndexRouteImport.update({
  id: '/pae-expert/',
  path: '/pae-expert/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const GdbCoverageIndexRoute = GdbCoverageIndexRouteImport.update({
  id: '/gdb-coverage/',
  path: '/gdb-coverage/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsReportedIndexRoute = FlagsReportedIndexRouteImport.update({
  id: '/flags-reported/',
  path: '/flags-reported/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorIndexRoute = CoordinatorIndexRouteImport.update({
  id: '/coordinator/',
  path: '/coordinator/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorProfileRoute = CoordinatorProfileRouteImport.update({
  id: '/coordinator/profile',
  path: '/coordinator/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/whatsapp-history': typeof WhatsappHistoryRoute
  '/coordinator/profile': typeof CoordinatorProfileRoute
  '/user/$userId': typeof UserUserIdRoute
  '/audit/': typeof AuditIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/coordinator/': typeof CoordinatorIndexRoute
  '/flags-reported/': typeof FlagsReportedIndexRoute
  '/gdb-coverage/': typeof GdbCoverageIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/home/': typeof HomeIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/pae-expert/': typeof PaeExpertIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/whatsapp-history': typeof WhatsappHistoryRoute
  '/coordinator/profile': typeof CoordinatorProfileRoute
  '/user/$userId': typeof UserUserIdRoute
  '/audit': typeof AuditIndexRoute
  '/auth': typeof AuthIndexRoute
  '/coordinator': typeof CoordinatorIndexRoute
  '/flags-reported': typeof FlagsReportedIndexRoute
  '/gdb-coverage': typeof GdbCoverageIndexRoute
  '/history': typeof HistoryIndexRoute
  '/home': typeof HomeIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/pae-expert': typeof PaeExpertIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/whatsapp-history': typeof WhatsappHistoryRoute
  '/coordinator/profile': typeof CoordinatorProfileRoute
  '/user/$userId': typeof UserUserIdRoute
  '/audit/': typeof AuditIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/coordinator/': typeof CoordinatorIndexRoute
  '/flags-reported/': typeof FlagsReportedIndexRoute
  '/gdb-coverage/': typeof GdbCoverageIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/home/': typeof HomeIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/pae-expert/': typeof PaeExpertIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/whatsapp-history'
    | '/coordinator/profile'
    | '/user/$userId'
    | '/audit/'
    | '/auth/'
    | '/coordinator/'
    | '/flags-reported/'
    | '/gdb-coverage/'
    | '/history/'
    | '/home/'
    | '/notifications/'
    | '/pae-expert/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/whatsapp-history'
    | '/coordinator/profile'
    | '/user/$userId'
    | '/audit'
    | '/auth'
    | '/coordinator'
    | '/flags-reported'
    | '/gdb-coverage'
    | '/history'
    | '/home'
    | '/notifications'
    | '/pae-expert'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/whatsapp-history'
    | '/coordinator/profile'
    | '/user/$userId'
    | '/audit/'
    | '/auth/'
    | '/coordinator/'
    | '/flags-reported/'
    | '/gdb-coverage/'
    | '/history/'
    | '/home/'
    | '/notifications/'
    | '/pae-expert/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WhatsappHistoryRoute: typeof WhatsappHistoryRoute
  CoordinatorProfileRoute: typeof CoordinatorProfileRoute
  UserUserIdRoute: typeof UserUserIdRoute
  AuditIndexRoute: typeof AuditIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CoordinatorIndexRoute: typeof CoordinatorIndexRoute
  FlagsReportedIndexRoute: typeof FlagsReportedIndexRoute
  GdbCoverageIndexRoute: typeof GdbCoverageIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  PaeExpertIndexRoute: typeof PaeExpertIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-history': {
      id: '/whatsapp-history'
      path: '/whatsapp-history'
      fullPath: '/whatsapp-history'
      preLoaderRoute: typeof WhatsappHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pae-expert/': {
      id: '/pae-expert/'
      path: '/pae-expert'
      fullPath: '/pae-expert/'
      preLoaderRoute: typeof PaeExpertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdb-coverage/': {
      id: '/gdb-coverage/'
      path: '/gdb-coverage'
      fullPath: '/gdb-coverage/'
      preLoaderRoute: typeof GdbCoverageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags-reported/': {
      id: '/flags-reported/'
      path: '/flags-reported'
      fullPath: '/flags-reported/'
      preLoaderRoute: typeof FlagsReportedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/': {
      id: '/coordinator/'
      path: '/coordinator'
      fullPath: '/coordinator/'
      preLoaderRoute: typeof CoordinatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/profile': {
      id: '/coordinator/profile'
      path: '/coordinator/profile'
      fullPath: '/coordinator/profile'
      preLoaderRoute: typeof CoordinatorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WhatsappHistoryRoute: WhatsappHistoryRoute,
  CoordinatorProfileRoute: CoordinatorProfileRoute,
  UserUserIdRoute: UserUserIdRoute,
  AuditIndexRoute: AuditIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  CoordinatorIndexRoute: CoordinatorIndexRoute,
  FlagsReportedIndexRoute: FlagsReportedIndexRoute,
  GdbCoverageIndexRoute: GdbCoverageIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  PaeExpertIndexRoute: PaeExpertIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
