/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappHistoryRouteImport } from './routes/whatsapp-history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemesIndexRouteImport } from './routes/schemes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PaeExpertIndexRouteImport } from './routes/pae-expert/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as FlagsReportedIndexRouteImport } from './routes/flags-reported/index'
import { Route as FertilizerIndexRouteImport } from './routes/fertilizer/index'
import { Route as CropCalendarIndexRouteImport } from './routes/crop-calendar/index'
import { Route as CoordinatorIndexRouteImport } from './routes/coordinator/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as UserUserIdRouteImport } from './routes/user/$userId'
import { Route as UserHistoryUserIdRouteImport } from './routes/user-history/$userId'
import { Route as CoordinatorProfileRouteImport } from './routes/coordinator/profile'

const WhatsappHistoryRoute = WhatsappHistoryRouteImport.update({
  id: '/whatsapp-history',
  path: '/whatsapp-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIndexRoute = SchemesIndexRouteImport.update({
  id: '/schemes/',
  path: '/schemes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaeExpertIndexRoute = PaeExpertIndexRouteImport.update({
  id: '/pae-expert/',
  path: '/pae-expert/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsReportedIndexRoute = FlagsReportedIndexRouteImport.update({
  id: '/flags-reported/',
  path: '/flags-reported/',
  getParentRoute: () => rootRouteImport,
} as any)
const FertilizerIndexRoute = FertilizerIndexRouteImport.update({
  id: '/fertilizer/',
  path: '/fertilizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropCalendarIndexRoute = CropCalendarIndexRouteImport.update({
  id: '/crop-calendar/',
  path: '/crop-calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorIndexRoute = CoordinatorIndexRouteImport.update({
  id: '/coordinator/',
  path: '/coordinator/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserHistoryUserIdRoute = UserHistoryUserIdRouteImport.update({
  id: '/user-history/$userId',
  path: '/user-history/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorProfileRoute = CoordinatorProfileRouteImport.update({
  id: '/coordinator/profile',
  path: '/coordinator/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/whatsapp-history': typeof WhatsappHistoryRoute
  '/coordinator/profile': typeof CoordinatorProfileRoute
  '/user-history/$userId': typeof UserHistoryUserIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/audit': typeof AuditIndexRoute
  '/auth': typeof AuthIndexRoute
  '/coordinator': typeof CoordinatorIndexRoute
  '/crop-calendar': typeof CropCalendarIndexRoute
  '/fertilizer': typeof FertilizerIndexRoute
  '/flags-reported': typeof FlagsReportedIndexRoute
  '/history': typeof HistoryIndexRoute
  '/home': typeof HomeIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/pae-expert': typeof PaeExpertIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/schemes': typeof SchemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/whatsapp-history': typeof WhatsappHistoryRoute
  '/coordinator/profile': typeof CoordinatorProfileRoute
  '/user-history/$userId': typeof UserHistoryUserIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/audit': typeof AuditIndexRoute
  '/auth': typeof AuthIndexRoute
  '/coordinator': typeof CoordinatorIndexRoute
  '/crop-calendar': typeof CropCalendarIndexRoute
  '/fertilizer': typeof FertilizerIndexRoute
  '/flags-reported': typeof FlagsReportedIndexRoute
  '/history': typeof HistoryIndexRoute
  '/home': typeof HomeIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/pae-expert': typeof PaeExpertIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/schemes': typeof SchemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/whatsapp-history': typeof WhatsappHistoryRoute
  '/coordinator/profile': typeof CoordinatorProfileRoute
  '/user-history/$userId': typeof UserHistoryUserIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/audit/': typeof AuditIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/coordinator/': typeof CoordinatorIndexRoute
  '/crop-calendar/': typeof CropCalendarIndexRoute
  '/fertilizer/': typeof FertilizerIndexRoute
  '/flags-reported/': typeof FlagsReportedIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/home/': typeof HomeIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/pae-expert/': typeof PaeExpertIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/schemes/': typeof SchemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/whatsapp-history'
    | '/coordinator/profile'
    | '/user-history/$userId'
    | '/user/$userId'
    | '/audit'
    | '/auth'
    | '/coordinator'
    | '/crop-calendar'
    | '/fertilizer'
    | '/flags-reported'
    | '/history'
    | '/home'
    | '/notifications'
    | '/pae-expert'
    | '/profile'
    | '/schemes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/whatsapp-history'
    | '/coordinator/profile'
    | '/user-history/$userId'
    | '/user/$userId'
    | '/audit'
    | '/auth'
    | '/coordinator'
    | '/crop-calendar'
    | '/fertilizer'
    | '/flags-reported'
    | '/history'
    | '/home'
    | '/notifications'
    | '/pae-expert'
    | '/profile'
    | '/schemes'
  id:
    | '__root__'
    | '/'
    | '/whatsapp-history'
    | '/coordinator/profile'
    | '/user-history/$userId'
    | '/user/$userId'
    | '/audit/'
    | '/auth/'
    | '/coordinator/'
    | '/crop-calendar/'
    | '/fertilizer/'
    | '/flags-reported/'
    | '/history/'
    | '/home/'
    | '/notifications/'
    | '/pae-expert/'
    | '/profile/'
    | '/schemes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WhatsappHistoryRoute: typeof WhatsappHistoryRoute
  CoordinatorProfileRoute: typeof CoordinatorProfileRoute
  UserHistoryUserIdRoute: typeof UserHistoryUserIdRoute
  UserUserIdRoute: typeof UserUserIdRoute
  AuditIndexRoute: typeof AuditIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CoordinatorIndexRoute: typeof CoordinatorIndexRoute
  CropCalendarIndexRoute: typeof CropCalendarIndexRoute
  FertilizerIndexRoute: typeof FertilizerIndexRoute
  FlagsReportedIndexRoute: typeof FlagsReportedIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  PaeExpertIndexRoute: typeof PaeExpertIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SchemesIndexRoute: typeof SchemesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-history': {
      id: '/whatsapp-history'
      path: '/whatsapp-history'
      fullPath: '/whatsapp-history'
      preLoaderRoute: typeof WhatsappHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/': {
      id: '/schemes/'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pae-expert/': {
      id: '/pae-expert/'
      path: '/pae-expert'
      fullPath: '/pae-expert'
      preLoaderRoute: typeof PaeExpertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags-reported/': {
      id: '/flags-reported/'
      path: '/flags-reported'
      fullPath: '/flags-reported'
      preLoaderRoute: typeof FlagsReportedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fertilizer/': {
      id: '/fertilizer/'
      path: '/fertilizer'
      fullPath: '/fertilizer'
      preLoaderRoute: typeof FertilizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-calendar/': {
      id: '/crop-calendar/'
      path: '/crop-calendar'
      fullPath: '/crop-calendar'
      preLoaderRoute: typeof CropCalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/': {
      id: '/coordinator/'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-history/$userId': {
      id: '/user-history/$userId'
      path: '/user-history/$userId'
      fullPath: '/user-history/$userId'
      preLoaderRoute: typeof UserHistoryUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/profile': {
      id: '/coordinator/profile'
      path: '/coordinator/profile'
      fullPath: '/coordinator/profile'
      preLoaderRoute: typeof CoordinatorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WhatsappHistoryRoute: WhatsappHistoryRoute,
  CoordinatorProfileRoute: CoordinatorProfileRoute,
  UserHistoryUserIdRoute: UserHistoryUserIdRoute,
  UserUserIdRoute: UserUserIdRoute,
  AuditIndexRoute: AuditIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  CoordinatorIndexRoute: CoordinatorIndexRoute,
  CropCalendarIndexRoute: CropCalendarIndexRoute,
  FertilizerIndexRoute: FertilizerIndexRoute,
  FlagsReportedIndexRoute: FlagsReportedIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  PaeExpertIndexRoute: PaeExpertIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SchemesIndexRoute: SchemesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
