import {ObjectId} from 'mongodb';

export enum AuditCategory {
  QUESTION = 'QUESTION',
  EXPERTS_CATEGORY = 'EXPERTS_CATEGORY',
  EXPERTS_MANAGEMENT = 'EXPERTS_MANAGEMENT',
  REQUEST_QUEUE = 'REQUEST_QUEUE',
  ANALYTICS = 'ANALYTICS',
  CROP_MANAGEMENT = 'CROP_MANAGEMENT',
  OUTREACH_REPORT = 'OUTREACH_REPORT',
  AGENTS_INTERFACE= 'AGENTS_INTERFACE', // PENDING, not on priority
  DOWNLOAD_REPORTS= 'DOWNLOAD_REPORTS',
  ANSWER= 'ANSWER',
  ADMIN_REPORT= 'ADMIN_REPORT',
  AI_GENERATED= 'AI_GENERATED',
  ROLE_MANAGEMENT = 'ROLE_MANAGEMENT',
  FARMER_MANAGEMENT = 'FARMER_MANAGEMENT',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
}

export enum AuditAction {
  // Farmer
  ADD_FARMER = 'ADD_FARMER',
  UPDATE_FARMER = 'UPDATE_FARMER',
  DELETE_FARMER = 'DELETE_FARMER',
  UPDATE_USER_VERIFICATION = 'UPDATE_USER_VERIFICATION',
  CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD',

  // Question
  QUESTION_ADD = 'QUESTION_ADD',
  QUESTION_UPDATE = 'QUESTION_UPDATE',
  QUESTION_DELETE = 'QUESTION_DELETE',
  QUESTION_BULK_CREATE = 'QUESTION_BULK_CREATE',
  QUESTION_BULK_UPDATE = 'QUESTION_BULK_UPDATE',
  QUESTION_BULK_DELETE = 'QUESTION_BULK_DELETE',
  REALLOCATE_QUESTIONS = 'REALLOCATE_QUESTIONS',
  QUESTION_HOLD = 'QUESTION_HOLD',
  QUESTION_UNHOLD = 'QUESTION_UNHOLD',
  QUESTION_PASS = 'QUESTION_PASS',
  PUSH_TO_AUDITOR = 'PUSH_TO_AUDITOR',
  NOTIFY_USER = 'NOTIFY_USER',
  DYNAMIC_CLOSED = 'DYNAMIC_CLOSED',
  CANCEL_QUEUE = 'CANCEL_QUEUE',
  BULK_PAE_ALLOCATE = 'BULK_PAE_ALLOCATE',
  REPLACE_QUEUE_EXPERT = 'REPLACE_QUEUE_EXPERT',
  CHECK_DUPLICATE = 'CHECK_DUPLICATE',
  CANCEL_DUPLICATE = 'CANCEL_DUPLICATE',
  APPROVE_AI_INITIAL_ANSWER = 'APPROVE_AI_INITIAL_ANSWER',

  //EXPERTS_CATEGORY
  EXPERTS_AUTO_ALLOCATE = 'EXPERTS_AUTO_ALLOCATE',
  SYSTEM_ALLOCATED = 'SYSTEM_ALLOCATED',
  SELECT_EXPERT = 'SELECT_EXPERT',
  SELECT_MODERATOR = 'SELECT_MODERATOR',
  DELETE_MODERATOR = 'DELETE_MODERATOR',
  DELETE_EXPERT = 'DELETE_EXPERT',
  EXPERTS_ADD_COMMENT = 'EXPERTS_ADD_COMMENT',
  // Gate keeper / auditor role queue
  SELECT_GATE_KEEPER = 'SELECT_GATE_KEEPER',
  DELETE_GATE_KEEPER = 'DELETE_GATE_KEEPER',
  SELECT_AUDITOR = 'SELECT_AUDITOR',
  DELETE_AUDITOR = 'DELETE_AUDITOR',
  TOGGLE_GATE_KEEPER_ALLOCATION = 'TOGGLE_GATE_KEEPER_ALLOCATION',
  TOGGLE_AUDITOR_ALLOCATION = 'TOGGLE_AUDITOR_ALLOCATION',

  //EXPERTS_MANAGEMENT
  BLOCK_EXPERT = 'BLOCK_EXPERT',
  UNBLOCK_EXPERT = 'UNBLOCK_EXPERT',
  ACTIVATE_EXPERT = 'ACTIVATE_EXPERT',
  DEACTIVATE_EXPERT = 'DEACTIVATE_EXPERT',
  ASSIGN_STF = 'ASSIGN_STF',
  REMOVE_STF = 'REMOVE_STF',

  //REQUEST_QUEUE,
  CHANGE_STATUS = 'CHANGE_STATUS',
  DELETE_REQUEST = 'DELETE_REQUEST',

  //ANALYTICS
  ANALYTICS_EXPORT_PDF = 'ANALYTICS_EXPORT_PDF', // button not functional yet, pending

  //CROP_MANAGEMENT
  ADD_CROP = 'ADD_CROP',
  UPDATE_CROP = 'UPDATE_CROP',
  CROP_BULK_CREATE = 'CROP_BULK_CREATE',

  //OUTREACH_REPORT
  SEND_OUTREACH_REPORT = 'SEND_OUTREACH_REPORT',

  //DOWNLOAD_REPORTS
  DOWNLOAD = 'DOWNLOAD',

  //ANSWER
  APPROVE_ANSWER = 'APPROVE_ANSWER',
  APPROVE_LLM_ANSWER = 'APPROVE_LLM_ANSWER',
  PUSH_TO_GDB = 'PUSH_TO_GDB',
  ANSWER_CREATED = 'ANSWER_CREATED',
  EDIT_FINAL_ANSWER = 'EDIT_FINAL_ANSWER',
  REROUTE_ANSWER = 'REROUTE_ANSWER',
  REROUTE_REJECTION = 'REROUTE_REJECTION',
  SUBMIT_ANSWER = 'SUBMIT_ANSWER',
  REVIEW_ANSWER = 'REVIEW_ANSWER',
  DELETE_ANSWER = 'DELETE_ANSWER',
  MODERATOR_REJECT_REROUTE = 'MODERATOR_REJECT_REROUTE',

  //ADMIN_REPORT
  SEND_DASHBOARD_REPORT = 'SEND_DASHBOARD_REPORT',

  //AI_GENERATED
  GENERATE_ANSWER = 'GENERATE_ANSWER',

  //ROLE_MANAGEMENT
  TOGGLE_ROLE = 'TOGGLE_ROLE',
  VERIFY_USER = 'VERIFY_USER',
}

export enum OutComeStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PARTIAL = 'PARTIAL',
}


export interface ModeratorAuditTrail {
  category: AuditCategory;
  action: AuditAction;
  actor: {
    id?: string | ObjectId;
    name?: string;
    email?: string;
    role?: string;
    avatar?: string;
    source?: string
  };

  context?: Record<string, any>;

  changes?: {
    before?: Record<string, any>;
    after?: Record<string, any>;
  };

  outcome?: {
    status: OutComeStatus;
    errorCode?: string;
    errorMessage?: string;
    errorName?: string;
    errorStack?: string; // truncated (top 3–5 lines)
  };

  createdAt?: Date;
}

export type AuditFilters = {
  page?: number;
  limit?: number;
  startDateTime?: string;
  endDateTime?: string;
  action?: string;
  category?: string;
  status?: string;
  sortOrder?: "asc" | "desc";
};