import { useEffect, useState } from 'react'
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts'
import { getLatestDigest, generateDigest } from '../client/api'
import { format } from 'date-fns'
import {
  FiFileText, FiCpu, FiRefreshCw, FiClock, FiAlertTriangle,
  FiTarget, FiGrid, FiThumbsUp, FiThumbsDown
} from 'react-icons/fi'

export default function WeeklyDigest() {
  const [digest, setDigest] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState('')

  const load = async () => {
    setLoading(true)
    setError('')
    try {
      const r = await getLatestDigest()
      setDigest(r)
    } catch (e: any) {
      if (e?.response?.status === 404) {
        setError('No digest generated yet. Click "Generate Digest" to create one.')
      } else {
        setError('Failed to load digest.')
      }
    }
    setLoading(false)
  }

  useEffect(() => { load() }, [])

  const handleGenerate = async () => {
    setGenerating(true)
    setError('')
    try {
      await generateDigest()
      await load()
    } catch (e: any) {
      setError('Generation failed: ' + (e?.response?.data?.detail || 'Check GROQ API key'))
    }
    setGenerating(false)
  }

  const formatDate = (d: string) => {
    try { return format(new Date(d), 'MMM d, yyyy') } catch { return d }
  }

  if (loading) return <div className="loading-wrap"><div className="spinner" /><span>Loading digest...</span></div>

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title"><FiFileText style={{ marginRight: '8px' }} /> Weekly Digest</h1>
        <p className="page-subtitle">AI-powered weekly summary of GDB feedback quality — generated by GROQ</p>
        <div className="page-actions">
          <button className="btn btn-primary" onClick={handleGenerate} disabled={generating}>
            {generating ? <><FiClock style={{ marginRight: '4px' }} /> Generating with GROQ...</> : <><FiCpu style={{ marginRight: '4px' }} /> Generate New Digest</>}
          </button>
          <button className="btn btn-secondary" onClick={load}><FiRefreshCw style={{ marginRight: '4px' }} /> Refresh</button>
        </div>
        {error && <div className="error-box mt-4"><FiAlertTriangle style={{ marginRight: '6px' }} /> {error}</div>}
      </div>

      {!digest ? (
        <div className="card">
          <div className="empty-state">
            <div className="empty-icon"><FiFileText size={48} color="var(--text-muted)" /></div>
            <p style={{ marginTop: '1rem' }}>No weekly digest available. Generate one using GROQ to see AI-powered insights.</p>
            <button className="btn btn-primary" style={{ marginTop: '1rem' }} onClick={handleGenerate} disabled={generating}>
              {generating ? <><FiClock style={{ marginRight: '4px' }} /> Generating...</> : <><FiCpu style={{ marginRight: '4px' }} /> Generate First Digest</>}
            </button>
          </div>
        </div>
      ) : (
        <>
          {/* Header */}
          <div className="card digest-card mb-6">
            <div className="card-body">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
                <div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Period</div>
                  <div style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                    {formatDate(digest.week_start)} → {formatDate(digest.week_end)}
                  </div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 2 }}>
                    Generated: {formatDate(digest.created_at)}
                  </div>
                </div>
                <div style={{ display: 'flex', gap: '2rem', flexWrap: 'wrap' }}>
                  <div style={{ textAlign: 'center' }}>
                    <div style={{ fontSize: '1.75rem', fontWeight: 800, color: digest.overall_helpfulness_score >= 60 ? 'var(--green-400)' : 'var(--red-400)' }}>
                      {digest.overall_helpfulness_score?.toFixed(1)}%
                    </div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>Overall Score</div>
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <div style={{ fontSize: '1.75rem', fontWeight: 800, color: 'var(--text-primary)' }}>
                      {digest.total_feedback_count?.toLocaleString()}
                    </div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>Responses</div>
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <div style={{ fontSize: '1.75rem', fontWeight: 800, color: 'var(--green-400)' }}>{digest.total_helpful}</div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px' }}>Helpful <FiThumbsUp size={10} /></div>
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <div style={{ fontSize: '1.75rem', fontWeight: 800, color: 'var(--red-400)' }}>{digest.total_not_helpful}</div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px' }}>Not Helpful <FiThumbsDown size={10} /></div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="grid-2 mb-6">
            {/* GROQ Analysis */}
            <div className="card">
              <div className="card-header">
                <span className="card-title"><FiCpu style={{ marginRight: '6px' }} /> GROQ AI Analysis</span>
                <span className="badge" style={{ background: 'rgba(168,85,247,0.15)', color: 'var(--purple-400)', border: '1px solid rgba(168,85,247,0.25)' }}>
                  llama-3.1-8b
                </span>
              </div>
              <div className="card-body">
                <div className="digest-analysis">
                  {digest.groq_analysis || 'No analysis available. Generate a new digest with GROQ configured.'}
                </div>
              </div>
            </div>

            {/* Recommendations */}
            <div className="card">
              <div className="card-header">
                <span className="card-title"><FiTarget style={{ marginRight: '6px' }} /> Actionable Recommendations</span>
              </div>
              <div className="card-body">
                {digest.groq_recommendations?.length > 0 ? (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                    {digest.groq_recommendations.map((rec: string, i: number) => (
                      <div key={i} className="recommendation-item">
                        <div className="rec-num">{i + 1}</div>
                        <span>{rec}</span>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>
                    No recommendations available. Generate digest with GROQ API key configured.
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Domain Breakdown Chart */}
          {digest.domain_breakdown?.length > 0 && (
            <div className="card mb-6">
              <div className="card-header">
                <span className="card-title"><FiGrid style={{ marginRight: '6px' }} /> Domain Performance This Week</span>
              </div>
              <div className="card-body">
                <ResponsiveContainer width="100%" height={220}>
                  <BarChart data={[...digest.domain_breakdown].sort((a, b) => a.helpfulness_score - b.helpfulness_score)}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="name" tick={{ fontSize: 11 }} />
                    <YAxis domain={[0, 100]} tickFormatter={v => `${v}%`} tick={{ fontSize: 11 }} />
                    <Tooltip
                      contentStyle={{ background: 'var(--bg-surface)', border: '1px solid var(--border-glass)', borderRadius: 8 }}
                      formatter={(v: any) => [`${Number(v).toFixed(1)}%`, 'Helpfulness']}
                    />
                    <Bar dataKey="helpfulness_score" radius={[4, 4, 0, 0]}>
                      {digest.domain_breakdown.map((d: any) => (
                        <rect key={d.name} fill={d.helpfulness_score >= 60 ? '#22c55e' : d.helpfulness_score >= 40 ? '#f59e0b' : '#ef4444'} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}

          {/* Lowest Rated Entries */}
          {digest.lowest_rated_entries?.length > 0 && (
            <div className="card">
              <div className="card-header">
                <span className="card-title"><FiAlertTriangle style={{ marginRight: '6px', color: 'var(--red-400)' }} /> Lowest Rated GDB Entries</span>
                <span className="badge badge-flagged">Priority Review</span>
              </div>
              <div className="data-table-wrap">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>GDB Entry ID</th>
                      <th>Question</th>
                      <th>Domain</th>
                      <th>Responses</th>
                      <th>Score</th>
                    </tr>
                  </thead>
                  <tbody>
                    {digest.lowest_rated_entries.map((e: any) => (
                      <tr key={e.gdb_entry_id}>
                        <td>
                          <code style={{ fontSize: '0.7rem', color: 'var(--text-muted)', fontFamily: 'JetBrains Mono, monospace' }}>
                            {e.gdb_entry_id}
                          </code>
                        </td>
                        <td><div className="table-question">{e.question || '—'}</div></td>
                        <td><span className="badge badge-domain">{e.domain || '—'}</span></td>
                        <td style={{ color: 'var(--text-secondary)' }}>{e.total_responses}</td>
                        <td>
                          <span style={{ color: 'var(--red-400)', fontWeight: 700 }}>
                            {e.helpfulness_score?.toFixed(1)}%
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  )
}
