commodities = [
    "Absinthe", "Ajwan", "Alasande Gram", "Almond(Badam)", "Alsandikai", 
    "Amaranthus", "Ambada Seed", "Ambady/Mesta", "Ambady/Mesta/Patson", 
    "Amla(Nelli Kai)", "Amphophalus", "Amranthas Red", "Antawala", 
    "Anthorium", "Apple", "Apricot(Jardalu/Khumani)", "Arecanut(Betelnut/Supari)", 
    "Arhar (Tur/Red Gram)(Whole)", "Arhar Dal(Tur Dal)", "Arhar(Tur/Red Gram)(Whole)", 
    "Asalia", "Ashgourd", "Ashwagandha", "Asparagus", "Astera", "Avare Dal", 
    "BOP", "Bael", "Bajra(Pearl Millet/Cumbu)", "Balekai", "Bamboo", "Banana", 
    "Banana - Green", "Barley (Jau)", "Barley(Jau)", "Bay leaf (Tejpatta)", 
    "Beans", "Beaten Rice", "Beetroot", "Bengal Gram Dal (Chana Dal)", 
    "Bengal Gram Dal(Chana Dal)", "Bengal Gram(Gram)(Whole)", 
    "Ber(Zizyphus/Borehannu)", "Betal Leaves", "Betelnuts", "Bhindi(Ladies Finger)", 
    "Bhui Amlaya", "Big Gram", "Binoula", "Bitter gourd", 
    "Black Gram (Urd Beans)(Whole)", "Black Gram Dal (Urd Dal)", 
    "Black Gram Dal(Urd Dal)", "Black Gram(Urd Beans)(Whole)", "Black pepper", 
    "Borehannu", "Bottle gourd", "Brahmi", "Bran", "Brinjal", "Broken Rice", 
    "Broomstick(Flower Broom)", "Bull", "Bullar", "Bunch Beans", "Butter", 
    "Cabbage", "Calendula", "Calf", "Cane", "Capsicum", "Cardamoms", 
    "Carnation", "Carrot", "Cashew Kernnel", "Cashewnuts", "Castor Oil", 
    "Castor Seed", "Cauliflower", "Chakotha", "Chapparad Avare", 
    "Chennangi (Whole)", "Chennangi Dal", "Cherry", "Chikoos(Sapota)", 
    "Chili Red", "Chilly Capsicum", "Chow Chow", "Chrysanthemum", 
    "Chrysanthemum(Loose)", "Cinamon(Dalchini)", "Cloves", "Cluster beans", 
    "Coca", "Cock", "Cocoa", "Coconut", "Coconut Oil", "Coconut Seed", 
    "Coffee", "Colacasia", "Copra", "Coriander(Leaves)", "Corriander seed", 
    "Cotton", "Cotton Seed", "Cow", "Cowpea (Lobia/Karamani)", 
    "Cowpea(Lobia/Karamani)", "Cowpea(Veg)", "Cucumbar(Kheera)", 
    "Cummin Seed(Jeera)", "Custard Apple (Sharifa)", "Custard Apple(Sharifa)", 
    "Daila(Chandni)", "Dal (Avare)", "Dalda", "Delha", "Dhaincha", "Drumstick", 
    "Dry Chillies", "Dry Fodder", "Dry Grapes", "Duck", "Duster Beans", "Egg", 
    "Egypian Clover(Barseem)", "Elephant Yam (Suran)", 
    "Elephant Yam(Suran)/Amorphophallus", "Field Pea", "Fig(Anjura/Anjeer)", 
    "Firewood", "Fish", "Flower Broom", "Foxtail Millet(Navane)", 
    "French Beans (Frasbean)", "French Beans(Frasbean)", "Galgal(Lemon)", 
    "Garlic", "Ghee", "Giloy", "Gingelly Oil", "Ginger(Dry)", "Ginger(Green)", 
    "Gladiolus Bulb", "Gladiolus Cut Flower", "Goat", "Gram Raw(Chholia)", 
    "Gramflour", "Grapes", "Green Avare (W)", "Green Avare(W)", "Green Chilli", 
    "Green Fodder", "Green Gram (Moong)(Whole)", "Green Gram Dal (Moong Dal)", 
    "Green Gram Dal(Moong Dal)", "Green Gram(Moong)(Whole)", "Green Peas", 
    "Ground Nut Oil", "Ground Nut Seed", "Groundnut", "Groundnut (Split)", 
    "Groundnut pods (raw)", "Groundnut pods(raw)", "Groundnut(Split)", "Guar", 
    "Guar Seed(Cluster Beans Seed)", "Guava", "Gudmar", "Guggal", "Gur(Jaggery)", 
    "Gurellu", "Haralekai", "He Buffalo", "Hen", "Hippe Seed", "Honey", 
    "Honge seed", "Hybrid Cumbu", "Indian Beans (Seam)", "Indian Beans(Seam)", 
    "Indian Colza(Sarson)", "Isabgul (Psyllium)", "Isabgul(Psyllium)", 
    "Jack Fruit", "Jack Fruit(Ripe)", "Jaffri", "Jaggery", "Jamamkhan", 
    "Jamun(Narale Hannu)", "Jarbara", "Jasmine", "Javi", "Jowar(Sorghum)", 
    "Jute", "Jute Seed", "Kabuli Chana(Chickpeas-White)", "Kacholam", "Kakada", 
    "Kalmegh", "Kankambra", "Karamani", "Karbuja(Musk Melon)", 
    "Kartali (Kantola)", "Kartali(Kantola)", "Kharif Mash", "Khoya", "Kinnow", 
    "Knool Khol", "Kodo Millet(Varagu)", "Kooth", "Kuchur", 
    "Kulthi(Horse Gram)", "Kutki", "Ladies Finger", "Lak(Teora)", 
    "Leafy Vegetable", "Lemon", "Lentil (Masur)(Whole)", "Lentil(Masur)(Whole)", 
    "Lilly", "Lime", "Linseed", "Lint", "Litchi", "Little gourd (Kundru)", 
    "Little gourd(Kundru)", "Long Melon(Kakri)", "Lotus", "Lotus Sticks", 
    "Lukad", "Mace", "Mahedi", "Mahua", "Mahua Seed(Hippe seed)", 
    "Maida Atta", "Maize", "Mango", "Mango (Raw-Ripe)", "Mango(Raw-Ripe)", 
    "Maragensu", "Marasebu", "Marget", "Marigold(Calcutta)", "Marigold(loose)", 
    "Mash", "Mashrooms", "Masur Dal", "Mataki", "Methi Seeds", "Methi(Leaves)", 
    "Millets", "Mint(Pudina)", "Moath Dal", "Mousambi(Sweet Lime)", "Muesli", 
    "Muleti", "Mustard", "Mustard Oil", "Myrobolan(Harad)", "Nearle Hannu", 
    "Neem Seed", "Nelli Kai", "Niger Seed (Ramtil)", "Niger Seed(Ramtil)", 
    "Nutmeg", "Onion", "Onion Green", "Orange", "Orchid", "Other Pulses", 
    "Other green and fresh vegetables", "Ox", "Paddy(Basmati)", 
    "Paddy(Common)", "Paddy(Dhan)(Basmati)", "Paddy(Dhan)(Common)", 
    "Palash flowers", "Papaya", "Papaya (Raw)", "Papaya(Raw)", "Patti Calcutta", 
    "Pea Pod/Pea Cod/हरी मटर", "Peach", "Pear(Marasebu)", "Peas Wet", 
    "Peas cod", "Peas(Dry)", "Pegeon Pea (Arhar Fali)", "Pegeon Pea(Arhar Fali)", 
    "Pepper garbled", "Pepper ungarbled", "Persimon(Japani Fal)", "Pigs", 
    "Pineapple", "Plum", "Pointed gourd (Parval)", "Pointed gourd(Parval)", 
    "Polherb", "Pomegranate", "Potato", "Pumpkin", "Pundi", "Pundi Seed", 
    "Pupadia", "Raddish", "Ragi (Finger Millet)", "Ragi(Finger Millet)", 
    "Raibel", "Rajgir", "Ram", "Rat Tail Radish (Mogari)", 
    "Rat Tail Radish(Mogari)", "Ratanjot", "Raya", "Red Gram", "Resinwood", 
    "Riccbcan", "Rice", "Ridgeguard(Tori)", "Rose(Local)", "Rose(Loose))", 
    "Rose(Tata)", "Round gourd", "Rubber", "Sabu Dan", "Safflower", "Saffron", 
    "Sajje", "Same/Savi", "Sanai/Sunhemp", "Sarasum", "Season Leaves", 
    "Seemebadnekai", "Seetapal", "Sesamum(Sesame,Gingelly,Til)", "She Buffalo", 
    "She Goat", "Sheep", "Siddota", "Skin And Hide", "Snakeguard", "Soanf", 
    "Soapnut(Antawala/Retha)", "Soji", "Sompu", "Soyabean", "Spinach", 
    "Sponge gourd", "Squash(Chappal Kadoo)", "Sugar", "Sugarcane", "Sunflower", 
    "Sunflower Seed", "Sunhemp", "Suram", "Surat Beans (Papadi)", 
    "Surat Beans(Papadi)", "Suva (Dill Seed)", "Suva(Dill Seed)", 
    "Suvarna Gadde", "Sweet Potato", "Sweet Pumpkin", "T.V. Cumbu", 
    "Tamarind Fruit", "Tamarind Seed", "Tapioca", "Taramira", "Tea", 
    "Tender Coconut", "Thinai (Italian Millet)", "Thinai(Italian Millet)", 
    "Thogrikai", "Thondekai", "Tinda", "Tobacco", "Tomato", "Torchwood", 
    "Toria", "Tube Flower", "Tube Rose(Double)", "Tube Rose(Loose)", 
    "Tube Rose(Single)", "Tulip", "Turmeric", "Turmeric (raw)", "Turmeric(raw)", 
    "Turnip", "Walnut", "Water Melon", "Wheat", "Wheat Atta", "White Muesli", 
    "White Peas", "White Pumpkin", "Wood", "Wool", "Yam", "Yam (Ratalu)", 
    "Yam(Ratalu)", "basil", "buttery", "dhawai flowers", "dried mango", 
    "gulli", "karanja seeds", "kutki", "liquor turmeric", "mango powder", 
    "nigella", "nigella seeds", "poppy seeds", "sanay", "spikenard", "stevia", 
    "stone pulverizer", "tulip", "vadang"
]